const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {diagnose,npmCliCandidates,npmCli,npmCiLogPath,captureNpmCi}=require('../src/ciDiagnosticOrgan');
const base={projectId:'github:owner/repo',repository:'owner/repo',commitSha:'a'.repeat(40),runId:'1',workflow:'Self-Test',job:'Windows Node 20',step:'Install locked dependencies',os:'Windows',nodeVersion:'v20.20.0',conclusion:'failure'};
test('diagnoses the exact tree-sitter Windows toolchain chain without authorizing repair or proof',()=>{const report=diagnose({...base,log:'npm ERR npm ci tree-sitter prebuild unavailable; native build node-gyp cannot recognize Visual Studio 18'});assert.equal(report.health.state,'degraded');assert.deepEqual(report.health.inhibitions,['claim-of-green','release','promotion']);assert.ok(report.diagnoses.some((item)=>item.id==='tree-sitter-windows-toolchain'));assert.equal(report.classification,'Insufficient Evidence');assert.equal(report.repairAuthorized,false);assert.equal(report.proofStageSatisfied,false);});
test('records checkout ownership separately and allows only bounded diagnosis',()=>{const report=diagnose({...base,step:'Checkout',log:'fatal: detected dubious ownership; use safe.directory'});assert.equal(report.diagnoses[0].category,'host-ownership');assert.match(report.diagnoses[0].next,/checkout-scoped/);});
test('rejects cross-project and unbound commit diagnosis',()=>{assert.throws(()=>diagnose({...base,projectId:'github:other/repo',log:''}),/Cross-project/);assert.throws(()=>diagnose({...base,commitSha:'latest',log:''}),/Exact commit/);});
test('unclassified failures remain degraded and explicitly uncertain',()=>{const report=diagnose({...base,log:'unknown failure'});assert.equal(report.unclassifiedFailure,true);assert.equal(report.health.state,'degraded');});
test('resolves the bundled npm CLI on this runtime and offers both supported Node layouts',()=>{const candidates=npmCliCandidates();assert.equal(candidates.length,2);assert.ok(candidates.some((candidate)=>candidate.endsWith(path.join('node_modules','npm','bin','npm-cli.js'))&&!candidate.includes(`${path.sep}lib${path.sep}`)));assert.ok(candidates.some((candidate)=>candidate.endsWith(path.join('lib','node_modules','npm','bin','npm-cli.js'))));assert.ok(fs.existsSync(npmCli()));});
test('reports an unresolvable npm CLI with every attempted layout instead of a single platform guess',()=>{assert.throws(()=>npmCli(path.join(path.sep,'nonexistent-node-root','bin','node')),(error)=>error.message.includes(path.join('node_modules','npm','bin','npm-cli.js'))&&error.message.includes(path.join('lib','node_modules','npm','bin','npm-cli.js')));});
test('preserves the wrapper\'s own start failure as typed, bounded evidence rather than an unclassified blank',(t)=>{const directory=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'crucible-ci-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const execPath=process.execPath;Object.defineProperty(process,'execPath',{value:path.join(path.sep,'nonexistent-node-root','bin','node'),configurable:true});try{const result=captureNpmCi({RUNNER_TEMP:directory});assert.equal(result.status,1);assert.equal(result.file,npmCiLogPath({RUNNER_TEMP:directory}));const report=diagnose({...base,log:fs.readFileSync(result.file,'utf8')});assert.equal(report.unclassifiedFailure,false);assert.ok(report.diagnoses.some((item)=>item.id==='npm-cli-resolution'));assert.equal(report.repairAuthorized,false);}finally{Object.defineProperty(process,'execPath',{value:execPath,configurable:true});}});
