const test = require('node:test');
const assert = require('node:assert/strict');
const { extractStepNames, generatedBlock, generatedWorkloadBlock, auditDocSync, syncReadme, MARKER_START, MARKER_END } = require('../src/docSync');

test('extractStepNames skips mechanical checkout steps and keeps everything else in order', () => {
  const workflow = [
    'jobs:',
    '  verify:',
    '    steps:',
    '      - name: Check out the caller repository',
    '        uses: actions/checkout@abc',
    '      - name: Check out the pinned Crucible engine',
    '        uses: actions/checkout@abc',
    '      - uses: actions/setup-node@abc',
    "      - name: Validate .thecrucible.json",
    '        run: node cli.js validate',
  ].join('\n');
  assert.deepEqual(extractStepNames(workflow), ['Validate .thecrucible.json']);
});

test('the real workflow file matches the currently committed README block', () => {
  const result = auditDocSync('.');
  assert.deepEqual(result, { inSync: true, findings: [] });
});

test('reports out of sync when the marker block is stale, and syncReadme fixes it', () => {
  const fs = require('node:fs');
  const os = require('node:os');
  const path = require('node:path');
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'crucible-docsync-'));
  fs.mkdirSync(path.join(root, '.github', 'workflows'), { recursive: true });
  fs.writeFileSync(path.join(root, '.github', 'workflows', 'the-crucible.yml'), [
    'jobs:',
    '  verify:',
    '    steps:',
    '      - name: Check out the caller repository',
    '      - name: One',
    '      - name: Two',
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(root, 'README.md'), [
    '# Project',
    '',
    MARKER_START,
    '1. Stale step.',
    MARKER_END,
    '',
    generatedWorkloadBlock(),
    '',
  ].join('\n'));
  const before = auditDocSync(root);
  assert.equal(before.inSync, false);
  assert.equal(before.findings.length, 1);
  assert.match(before.findings[0].type, /out of date/);
  const result = syncReadme(root);
  assert.equal(result.changed, true);
  const after = auditDocSync(root);
  assert.deepEqual(after, { inSync: true, findings: [] });
  assert.equal(generatedBlock(root), [MARKER_START, '1. One.', '2. Two.', MARKER_END].join('\n'));
});

test('CRLF line endings (as Windows checkouts produce) are not treated as drift', () => {
  const fs = require('node:fs');
  const os = require('node:os');
  const path = require('node:path');
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'crucible-docsync-'));
  fs.mkdirSync(path.join(root, '.github', 'workflows'), { recursive: true });
  fs.writeFileSync(path.join(root, '.github', 'workflows', 'the-crucible.yml'), [
    'jobs:',
    '  verify:',
    '    steps:',
    '      - name: One',
    '      - name: Two',
    '',
  ].join('\r\n'));
  const crlfBlock = [MARKER_START, '1. One.', '2. Two.', MARKER_END].join('\r\n');
  const crlfWorkloadBlock = generatedWorkloadBlock().split('\n').join('\r\n');
  fs.writeFileSync(path.join(root, 'README.md'), ['# Project', '', crlfBlock, '', crlfWorkloadBlock, ''].join('\r\n'));
  assert.deepEqual(auditDocSync(root), { inSync: true, findings: [] });
  assert.deepEqual(syncReadme(root), { changed: false });
});

test('README workload field list matches src/config.js WORKLOAD_FIELDS', () => {
  const result = auditDocSync('.');
  assert.deepEqual(result, { inSync: true, findings: [] });
});

test('reports stale workload field docs and syncReadme fixes them without touching the workflow-steps block', () => {
  const fs = require('node:fs');
  const os = require('node:os');
  const path = require('node:path');
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'crucible-docsync-'));
  fs.mkdirSync(path.join(root, '.github', 'workflows'), { recursive: true });
  fs.writeFileSync(path.join(root, '.github', 'workflows', 'the-crucible.yml'), [
    'jobs:',
    '  verify:',
    '    steps:',
    '      - name: One',
    '',
  ].join('\n'));
  const workflowBlock = [MARKER_START, '1. One.', MARKER_END].join('\n');
  fs.writeFileSync(path.join(root, 'README.md'), [
    '# Project',
    '',
    workflowBlock,
    '',
    '<!-- CRUCIBLE_WORKLOAD_FIELDS:START (generated by `npm run docs:sync` - do not edit by hand) -->',
    '- `workers`: stale description, from 1 through 99. Default: 1.',
    '<!-- CRUCIBLE_WORKLOAD_FIELDS:END -->',
    '',
  ].join('\n'));
  const before = auditDocSync(root);
  assert.equal(before.inSync, false);
  assert.equal(before.findings.length, 1);
  assert.match(before.findings[0].type, /workload field list is out of date/);
  const result = syncReadme(root);
  assert.equal(result.changed, true);
  assert.deepEqual(auditDocSync(root), { inSync: true, findings: [] });
  // The untouched workflow-steps block must survive the workload-only fix.
  assert.match(fs.readFileSync(path.join(root, 'README.md'), 'utf8'), /1\. One\./);
});

test('syncReadme refuses to guess where the workload field list belongs when its markers are missing', () => {
  const fs = require('node:fs');
  const os = require('node:os');
  const path = require('node:path');
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'crucible-docsync-'));
  fs.mkdirSync(path.join(root, '.github', 'workflows'), { recursive: true });
  fs.writeFileSync(path.join(root, '.github', 'workflows', 'the-crucible.yml'), [
    'jobs:',
    '  verify:',
    '    steps:',
    '      - name: One',
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(root, 'README.md'), [MARKER_START, '1. One.', MARKER_END].join('\n'));
  assert.throws(() => syncReadme(root), /missing the generated workload field markers/);
  assert.deepEqual(auditDocSync(root).inSync, false);
});

test('syncReadme refuses to guess where the list belongs when markers are missing', () => {
  const fs = require('node:fs');
  const os = require('node:os');
  const path = require('node:path');
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'crucible-docsync-'));
  fs.mkdirSync(path.join(root, '.github', 'workflows'), { recursive: true });
  fs.writeFileSync(path.join(root, '.github', 'workflows', 'the-crucible.yml'), '');
  fs.writeFileSync(path.join(root, 'README.md'), '# Project\n');
  assert.throws(() => syncReadme(root), /missing the generated workflow-steps markers/);
  assert.deepEqual(auditDocSync(root).inSync, false);
});
