import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.*;import java.util.*;import javax.lang.model.element.*;import javax.tools.*;import com.sun.source.tree.*;import com.sun.source.util.*;
class JavaSemanticAnalyzer{
  static String b(String value){return Base64.getUrlEncoder().withoutPadding().encodeToString(value.getBytes(StandardCharsets.UTF_8));}
  // Declared unchecked deliberately: hash is called from inside TreePathScanner overrides,
  // which cannot propagate a checked exception, so `throws Exception` here made the whole
  // analyzer fail to compile. A missing SHA-256 is a broken JDK, not a recoverable case.
  static String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(java.security.NoSuchAlgorithmException error){throw new IllegalStateException("SHA-256 is unavailable in this JDK",error);}}
  public static void main(String[] args)throws Exception{if(args.length<3)throw new IllegalArgumentException("root, project, and files required");Path root=Path.of(args[0]).toAbsolutePath().normalize();String project=args[1];JavaCompiler compiler=ToolProvider.getSystemJavaCompiler();if(compiler==null)throw new IllegalStateException("JDK compiler unavailable");List<File> sourceFiles=new ArrayList<>();for(int i=2;i<args.length;i++){Path target=root.resolve(args[i]).normalize();if(!target.startsWith(root))throw new SecurityException("Analysis path escapes project root");sourceFiles.add(target.toFile());}try(StandardJavaFileManager manager=compiler.getStandardFileManager(null,null,StandardCharsets.UTF_8)){JavacTask task=(JavacTask)compiler.getTask(null,manager,null,List.of("-proc:none"),null,manager.getJavaFileObjectsFromFiles(sourceFiles));Iterable<? extends CompilationUnitTree> units=task.parse();task.analyze();Trees trees=Trees.instance(task);System.out.println("META|"+b(project)+"|"+b(System.getProperty("java.version")));for(CompilationUnitTree unit:units){Path absolute=Path.of(unit.getSourceFile().toUri()).toAbsolutePath().normalize();String relative=root.relativize(absolute).toString();String content=Files.readString(absolute);System.out.println("FILE|"+b(relative)+"|"+hash(content));new TreePathScanner<Void,Void>(){String current=null;public Void visitMethod(MethodTree node,Void unused){Element element=trees.getElement(getCurrentPath());String prior=current;current=element==null?relative+"#"+node.getName():relative+"#"+element.toString();long start=trees.getSourcePositions().getStartPosition(unit,node),end=trees.getSourcePositions().getEndPosition(unit,node);String params=String.join(",",node.getParameters().stream().map(p->p.getName().toString()).toList());System.out.println("FUNCTION|"+b(relative)+"|"+b(current)+"|"+start+"|"+end+"|"+b(params));super.visitMethod(node,unused);current=prior;return null;}public Void visitMethodInvocation(MethodInvocationTree node,Void unused){Element element=trees.getElement(getCurrentPath());String name=element==null?node.getMethodSelect().toString():element.getSimpleName().toString();String target=element==null?"":relative+"#"+element.toString();long start=trees.getSourcePositions().getStartPosition(unit,node),end=trees.getSourcePositions().getEndPosition(unit,node);System.out.println("CALL|"+b(relative)+"|"+b(current==null?"":current)+"|"+b(name)+"|"+b(target)+"|"+start+"|"+end);if(Set.of("exec","start","execute").contains(name.toLowerCase()))System.out.println("FINDING|"+b(relative)+"|"+b(name)+"|"+start+"|"+end+"|"+hash(content));return super.visitMethodInvocation(node,unused);}}.scan(unit,null);}}}
}
