const crypto=require('node:crypto');const fs=require('node:fs');const path=require('node:path');const {spawnSync}=require('node:child_process');
const sha=(value)=>crypto.createHash('sha256').update(value).digest('hex');
const RULES=Object.freeze([
  {id:'git-checkout-ownership',category:'host-ownership',patterns:[/dubious ownership/i,/safe\.directory/i],cause:'Git rejected a checkout owned by a different host identity.',next:'Use a checkout-scoped safe.directory override only after exact-path validation.'},
  {id:'tree-sitter-windows-toolchain',category:'native-dependency-toolchain',patterns:[/tree-sitter/i,/visual studio (?:18|2026)/i],cause:'tree-sitter fell back to a native build on a Windows image whose Visual Studio generation is not recognized by the dependency toolchain.',next:'Use a supported pinned Windows image or a dependency release with a matching prebuilt binary; do not remove runtime coverage.'},
  {id:'locked-dependency-install',category:'dependency-install',patterns:[/npm (?:err|error|ci)/i,/node-gyp|prebuild|native build/i],cause:'Locked dependency installation failed before Crucible tests could execute.',next:'Repair the bounded dependency/toolchain condition and rerun the complete exact-tip matrix.'},
  {id:'missing-module',category:'dependency-resolution',patterns:[/module_not_found|cannot find module/i],cause:'A declared runtime module was unavailable to the test process.',next:'Verify locked installation and declared dependency custody before changing tests.'},
]);
function requireText(value,name){if(typeof value!=='string'||!value.trim())throw new Error(`${name} is required.`);return value;}
function diagnose({projectId,repository,commitSha,runId,workflow,job,step,os,nodeVersion,conclusion,log=''}){requireText(projectId,'projectId');requireText(repository,'repository');if(projectId!==`github:${repository}`)throw new Error('Cross-project CI diagnosis is forbidden.');if(!/^[a-f0-9]{40}$/.test(commitSha||''))throw new Error('Exact commit SHA is required.');const bounded=String(log).slice(0,4*1024*1024),matches=RULES.filter((rule)=>rule.patterns.every((pattern)=>pattern.test(bounded))).map(({patterns,...rule})=>rule);const failure=conclusion!=='success';return{schemaVersion:1,projectId,repository,commitSha,runId:String(runId||''),workflow:requireText(workflow,'workflow'),job:requireText(job,'job'),step:requireText(step,'step'),environment:{os:String(os||'unknown'),nodeVersion:String(nodeVersion||'unknown')},conclusion:failure?'failure':'success',health:{organ:'hosted-ci',state:failure?'degraded':'healthy',inhibitions:failure?['claim-of-green','release','promotion']:[]},diagnoses:matches,unclassifiedFailure:failure&&matches.length===0,logSha256:sha(bounded),logBytes:Buffer.byteLength(bounded),classification:'Insufficient Evidence',proofStageSatisfied:false,promotionAuthorized:false,repairAuthorized:false,independentVerificationSatisfied:false};}
function npmCli(){const candidate=path.join(path.dirname(process.execPath),'node_modules','npm','bin','npm-cli.js');if(!fs.existsSync(candidate))throw new Error(`Locked npm CLI was not found beside Node: ${candidate}`);return candidate;}
function captureNpmCi(environment=process.env){const result=spawnSync(process.execPath,[npmCli(),'ci'],{encoding:'utf8',shell:false,windowsHide:true,maxBuffer:4*1024*1024});const output=`${result.stdout||''}${result.stderr||''}`;process.stdout.write(output);const root=environment.RUNNER_TEMP||process.cwd(),file=path.join(root,'crucible-npm-ci.log');fs.writeFileSync(file,output,{mode:0o600});return{status:result.status??1,file};}
function writeLocalReport(logFile,environment=process.env){const log=logFile&&fs.existsSync(logFile)?fs.readFileSync(logFile,'utf8'):'diagnostic log unavailable';const report=diagnose({projectId:environment.CRUCIBLE_PROJECT_ID||`github:${environment.GITHUB_REPOSITORY}`,repository:environment.GITHUB_REPOSITORY,commitSha:environment.CRUCIBLE_DIAGNOSTIC_SHA||environment.GITHUB_SHA,runId:environment.GITHUB_RUN_ID,workflow:environment.GITHUB_WORKFLOW||'The Crucible Self-Test',job:environment.CRUCIBLE_CI_JOB||'The Crucible',step:environment.CRUCIBLE_FAILED_STEP||'Install locked dependencies',os:environment.RUNNER_OS,nodeVersion:process.version,conclusion:'failure',log});fs.writeFileSync('ci-diagnostic-report.json',`${JSON.stringify(report,null,2)}\n`,{mode:0o600});return report;}
if(require.main===module){try{const command=process.argv[2];if(command==='capture-npm-ci'){const result=captureNpmCi();process.exitCode=result.status;}else if(command==='diagnose-local'){console.log(JSON.stringify(writeLocalReport(process.argv[3]),null,2));}else throw new Error('Usage: ciDiagnosticOrgan.js <capture-npm-ci|diagnose-local> [log-file]');}catch(error){console.error(`[The Crucible] CI diagnostic organ failed closed: ${error.message}`);process.exitCode=1;}}
module.exports={RULES,diagnose,captureNpmCi,writeLocalReport};
