const crypto=require('node:crypto');const fs=require('node:fs');const path=require('node:path');const {spawnSync}=require('node:child_process');
const {UNCODED,codesInText,describeCode}=require('./failureCodes');
const sha=(value)=>crypto.createHash('sha256').update(value).digest('hex');
const RULES=Object.freeze([
  {id:'git-checkout-ownership',category:'host-ownership',patterns:[/dubious ownership/i,/safe\.directory/i],cause:'Git rejected a checkout owned by a different host identity.',next:'Use a checkout-scoped safe.directory override only after exact-path validation.'},
  {id:'tree-sitter-windows-toolchain',category:'native-dependency-toolchain',patterns:[/tree-sitter/i,/visual studio (?:18|2026)/i],cause:'tree-sitter fell back to a native build on a Windows image whose Visual Studio generation is not recognized by the dependency toolchain.',next:'Use a supported pinned Windows image or a dependency release with a matching prebuilt binary; do not remove runtime coverage.'},
  {id:'locked-dependency-install',category:'dependency-install',patterns:[/npm (?:err|error|ci)/i,/node-gyp|prebuild|native build/i],cause:'Locked dependency installation failed before Crucible tests could execute.',next:'Repair the bounded dependency/toolchain condition and rerun the complete exact-tip matrix.'},
  {id:'missing-module',category:'dependency-resolution',patterns:[/module_not_found|cannot find module/i],cause:'A declared runtime module was unavailable to the test process.',next:'Verify locked installation and declared dependency custody before changing tests.'},
  {id:'npm-cli-resolution',category:'ci-harness',patterns:[/locked npm cli was not found/i],cause:'The install wrapper could not locate the Node distribution\'s bundled npm CLI in this platform\'s layout, so the locked install never started.',next:'Resolve npm across every supported Node layout before installing; never bypass or weaken the locked install to get past it.'},
]);
function requireText(value,name){if(typeof value!=='string'||!value.trim())throw new Error(`${name} is required.`);return value;}
function diagnose({projectId,repository,commitSha,runId,workflow,job,step,os,nodeVersion,conclusion,log=''}){requireText(projectId,'projectId');requireText(repository,'repository');if(projectId!==`github:${repository}`)throw new Error('Cross-project CI diagnosis is forbidden.');if(!/^[a-f0-9]{40}$/.test(commitSha||''))throw new Error('Exact commit SHA is required.');const bounded=String(log).slice(0,4*1024*1024);const failure=conclusion!=='success';
// Codes first. A Crucible failure declares what it is, so classifying it is a lookup that
// survives rewording; the pattern rules below are kept only for the failures that are not ours
// to code - npm, git and the Node runtime itself, which will never carry a CRU code.
const coded=codesInText(bounded).map((code)=>({id:code,category:describeCode(code).category,cause:describeCode(code).meaning,next:describeCode(code).next,remedy:describeCode(code).remedy,source:'failure-code'}));
const patterned=RULES.filter((rule)=>rule.patterns.every((pattern)=>pattern.test(bounded))).map(({patterns,...rule})=>({...rule,source:'pattern-rule'}));
// A failure with nothing to say about it is the report the owner rejected outright. When a
// failure reaches here unclassified it is still given a code - CRU-0000 - which names the gap
// as a defect in coverage and says how to close it. `unclassifiedFailure` is retained so an
// older reader is not silently misled, but it is now a property of the codebase rather than a
// dead end: something failed on a path nobody has coded yet, and that is actionable.
const uncoded=failure&&!coded.length&&!patterned.length;
const matches=uncoded?[{id:UNCODED,category:describeCode(UNCODED).category,cause:describeCode(UNCODED).meaning,next:describeCode(UNCODED).next,remedy:describeCode(UNCODED).remedy,source:'coverage-gap',detail:`Classified against ${Buffer.byteLength(bounded)} byte(s) of log for step "${step}". If that log cannot contain the failure, the diagnostic organ was handed the wrong one.`}]:[...coded,...patterned];return{schemaVersion:2,projectId,repository,commitSha,runId:String(runId||''),workflow:requireText(workflow,'workflow'),job:requireText(job,'job'),step:requireText(step,'step'),environment:{os:String(os||'unknown'),nodeVersion:String(nodeVersion||'unknown')},conclusion:failure?'failure':'success',health:{organ:'hosted-ci',state:failure?'degraded':'healthy',inhibitions:failure?['claim-of-green','release','promotion']:[]},diagnoses:matches,unclassifiedFailure:uncoded,logSha256:sha(bounded),logBytes:Buffer.byteLength(bounded),classification:'Insufficient Evidence',proofStageSatisfied:false,promotionAuthorized:false,repairAuthorized:false,independentVerificationSatisfied:false};}
// Windows ships npm beside node.exe; POSIX Node distributions keep it one level up under lib/. Both are supported runtimes, so both layouts must resolve.
function npmCliCandidates(execPath=process.execPath){const directory=path.dirname(execPath);return[path.join(directory,'node_modules','npm','bin','npm-cli.js'),path.resolve(directory,'..','lib','node_modules','npm','bin','npm-cli.js')];}
function npmCli(execPath=process.execPath){const candidates=npmCliCandidates(execPath),resolved=candidates.find((candidate)=>fs.existsSync(candidate));if(!resolved)throw new Error(`Locked npm CLI was not found beside Node: ${candidates.join(', ')}`);return resolved;}
function npmCiLogPath(environment=process.env){return path.join(environment.RUNNER_TEMP||process.cwd(),'crucible-npm-ci.log');}
function captureNpmCi(environment=process.env){let output,status;try{const result=spawnSync(process.execPath,[npmCli(),'ci'],{encoding:'utf8',shell:false,windowsHide:true,maxBuffer:4*1024*1024});output=`${result.stdout||''}${result.stderr||''}`;status=result.status??1;}catch(error){output=`[The Crucible] Locked install could not be started: ${error.message}\n`;status=1;}process.stdout.write(output);const file=npmCiLogPath(environment);fs.writeFileSync(file,output,{mode:0o600});return{status,file};}
// Reads every log it is given rather than one. The self-test workflow hands this the npm-install
// log whichever step failed, so a failure four steps later was diagnosed against output that
// could not mention it. The failing Crucible process now records its own coded failure to
// CRUCIBLE_FAILURE_LOG, and that file is read alongside the install log so the organ sees the
// failure it is being asked to explain.
function writeLocalReport(logFile,environment=process.env){const files=[logFile,environment.CRUCIBLE_FAILURE_LOG].filter((file)=>file&&fs.existsSync(file));const log=files.length?files.map((file)=>fs.readFileSync(file,'utf8')).join('\n'):'diagnostic log unavailable';const report=diagnose({projectId:environment.CRUCIBLE_PROJECT_ID||`github:${environment.GITHUB_REPOSITORY}`,repository:environment.GITHUB_REPOSITORY,commitSha:environment.CRUCIBLE_DIAGNOSTIC_SHA||environment.GITHUB_SHA,runId:environment.GITHUB_RUN_ID,workflow:environment.GITHUB_WORKFLOW||'The Crucible Self-Test',job:environment.CRUCIBLE_CI_JOB||'The Crucible',step:environment.CRUCIBLE_FAILED_STEP||'Install locked dependencies',os:environment.RUNNER_OS,nodeVersion:process.version,conclusion:'failure',log});fs.writeFileSync('ci-diagnostic-report.json',`${JSON.stringify(report,null,2)}\n`,{mode:0o600});return report;}
if(require.main===module){try{const command=process.argv[2];if(command==='capture-npm-ci'){const result=captureNpmCi();process.exitCode=result.status;}else if(command==='diagnose-local'){console.log(JSON.stringify(writeLocalReport(process.argv[3]),null,2));}else throw new Error('Usage: ciDiagnosticOrgan.js <capture-npm-ci|diagnose-local> [log-file]');}catch(error){console.error(`[The Crucible] CI diagnostic organ failed closed: ${error.message}`);process.exitCode=1;}}
module.exports={RULES,diagnose,npmCliCandidates,npmCli,npmCiLogPath,captureNpmCi,writeLocalReport};
