const crypto=require('node:crypto');const fs=require('node:fs');const path=require('node:path');const {ProductionWorkflowActuator}=require('./ecosystem');
const sha=(value)=>crypto.createHash('sha256').update(value).digest('hex');
const LANGUAGE_PROFILES=Object.freeze([
  {id:'javascript',extensions:['.js','.mjs','.cjs'],signals:[['dynamic-code-execution',/\beval\s*\(/g,'injectionPaths'],['unsafe-html-assignment',/\.innerHTML\s*=/g,'dataFlow']]},
  {id:'typescript',extensions:['.ts','.tsx'],signals:[['dynamic-code-execution',/\beval\s*\(/g,'injectionPaths'],['unsafe-html-assignment',/\.innerHTML\s*=/g,'dataFlow']]},
  {id:'python',extensions:['.py'],signals:[['shell-command-execution',/subprocess\.(?:run|Popen|call)\([^\n]*shell\s*=\s*True/g,'injectionPaths'],['dynamic-code-execution',/\b(?:eval|exec)\s*\(/g,'injectionPaths']]},
  {id:'java',extensions:['.java'],signals:[['process-command-execution',/Runtime\.getRuntime\(\)\.exec\s*\(/g,'injectionPaths'],['weak-randomness',/new\s+Random\s*\(/g,'authenticationBoundaries']]},
  {id:'c',extensions:['.c','.h'],signals:[['unbounded-copy',/\b(?:strcpy|strcat|gets)\s*\(/g,'dataFlow'],['format-string-risk',/\bprintf\s*\(\s*[A-Za-z_][\w]*/g,'injectionPaths']]},
  {id:'cpp',extensions:['.cc','.cpp','.cxx','.hpp','.hh'],signals:[['unbounded-copy',/\b(?:strcpy|strcat|gets)\s*\(/g,'dataFlow'],['process-command-execution',/\b(?:system|popen)\s*\(/g,'injectionPaths']]},
  {id:'csharp',extensions:['.cs'],signals:[['process-command-execution',/Process\.Start\s*\(/g,'injectionPaths'],['weak-randomness',/new\s+Random\s*\(/g,'authenticationBoundaries']]},
  {id:'powershell',extensions:['.ps1','.psm1'],signals:[['dynamic-command-execution',/\b(?:Invoke-Expression|iex)\b/gi,'injectionPaths'],['plaintext-secret-conversion',/ConvertTo-SecureString[^\n]*-AsPlainText/gi,'secrets']]},
  {id:'shell',extensions:['.sh','.bash'],signals:[['dynamic-command-execution',/\beval\s+/g,'injectionPaths'],['unquoted-expansion',/(?:^|[;&|]\s*)rm\s+-[^\n]*\$\w+/gm,'injectionPaths']]},
  {id:'html',extensions:['.html','.htm'],signals:[['inline-script-handler',/\son[a-z]+\s*=/gi,'injectionPaths'],['unsafe-new-window',/target\s*=\s*["']_blank["'](?![^>]*\brel\s*=)/gi,'authenticationBoundaries']]},
  {id:'css',extensions:['.css'],signals:[['insecure-import',/@import\s+(?:url\()?\s*["']?http:\/\//gi,'dependencyRisk']]},
]);
function languageFor(file){const lower=file.toLowerCase();if(/\.(jsx|tsx)$/.test(lower)||/(?:^|[/\\])(?:components|react)[/\\]/i.test(file))return'react';if(/(?:^|[/\\])(?:django|templates)[/\\]/i.test(file)&&lower.endsWith('.py'))return'django';return LANGUAGE_PROFILES.find((profile)=>profile.extensions.includes(path.extname(lower)))?.id||null;}
function profileFor(language){if(language==='react')return{id:'react',extensions:['.jsx','.tsx'],signals:LANGUAGE_PROFILES[0].signals};if(language==='django')return{id:'django',extensions:['.py'],signals:[...LANGUAGE_PROFILES[2].signals,['unsafe-debug-mode',/\bDEBUG\s*=\s*True\b/g,'authenticationBoundaries']]};return LANGUAGE_PROFILES.find((profile)=>profile.id===language);}
function buildThreatContext(files,dependencyManifest={}){const context={dataFlow:[],dependencyRisk:[],authenticationBoundaries:[],secrets:[],injectionPaths:[],crossFileConsequences:[]};const findings=[];for(const [file,content] of Object.entries(files)){const language=languageFor(file);const profile=profileFor(language);if(!profile)continue;for(const [kind,pattern,dimension] of profile.signals){pattern.lastIndex=0;for(const match of content.matchAll(pattern)){const finding={id:`finding-${sha(`${file}\0${kind}\0${match.index}\0${match[0]}`).slice(0,24)}`,language,file,kind,offset:match.index,matchedHash:sha(match[0]),baseSha256:sha(content),boundary:file,dimension};findings.push(finding);context[dimension].push(finding.id);}}}for(const [name,version] of Object.entries(dependencyManifest))context.dependencyRisk.push({name,version,source:'declared-manifest'});const byKind=new Map();for(const finding of findings){const list=byKind.get(finding.kind)||[];list.push(finding.file);byKind.set(finding.kind,list);}for(const [kind,paths] of byKind)if(new Set(paths).size>1)context.crossFileConsequences.push({kind,files:[...new Set(paths)].sort()});return{findings,context,repositoryHash:sha(JSON.stringify(Object.entries(files).sort()))};}
class InMemoryCodeWorkspace{constructor(files){this.files={...files};this.rollbacks=new Map();}snapshot(){return{...this.files};}read(file){if(!(file in this.files))throw new Error(`Unknown file ${file}.`);return this.files[file];}apply(plan){const current=this.read(plan.file);if(sha(current)!==plan.baseSha256)throw new Error('Repair base hash changed.');for(const dependency of plan.dependencies)if(sha(this.read(dependency.file))!==dependency.sha256)throw new Error(`Repair dependency changed: ${dependency.file}.`);if(!current.includes(plan.before))throw new Error('Repair boundary is not present.');const next=current.replace(plan.before,plan.after);if(next===current)throw new Error('Repair made no change.');const token=`rollback-${sha(`${plan.file}\0${current}`).slice(0,24)}`;this.rollbacks.set(token,{file:plan.file,content:current});this.files[plan.file]=next;return{changeHash:sha(next),rollbackToken:token,resultSha256:sha(next)};}rollback(token){const saved=this.rollbacks.get(token);if(!saved)return{restored:false};this.files[saved.file]=saved.content;this.rollbacks.delete(token);return{restored:true,resultSha256:sha(saved.content)};}}
class FileSystemCodeWorkspace{
  constructor({root,files}){this.root=path.resolve(root);this.files=[...new Set(files)].sort();this.rollbacks=new Map();for(const file of this.files)this.resolve(file);}
  resolve(file){if(typeof file!=='string'||path.isAbsolute(file)||file.includes('\0'))throw new Error('Workspace files must be relative paths.');const target=path.resolve(this.root,file);if(target!==this.root&&!target.startsWith(`${this.root}${path.sep}`))throw new Error('Workspace path escapes repository root.');return target;}
  snapshot(){return Object.fromEntries(this.files.map((file)=>[file,this.read(file)]));}
  read(file){if(!this.files.includes(file))throw new Error(`Unregistered workspace file ${file}.`);return fs.readFileSync(this.resolve(file),'utf8');}
  writeAtomic(file,content){const target=this.resolve(file);const temporary=`${target}.crucible-${process.pid}-${crypto.randomBytes(6).toString('hex')}.tmp`;fs.writeFileSync(temporary,content,{encoding:'utf8',mode:fs.statSync(target).mode});fs.renameSync(temporary,target);}
  apply(plan){const current=this.read(plan.file);if(sha(current)!==plan.baseSha256)throw new Error('Repair base hash changed.');for(const dependency of plan.dependencies)if(sha(this.read(dependency.file))!==dependency.sha256)throw new Error(`Repair dependency changed: ${dependency.file}.`);if(!current.includes(plan.before))throw new Error('Repair boundary is not present.');const next=current.replace(plan.before,plan.after);if(next===current)throw new Error('Repair made no change.');const token=`rollback-${sha(`${plan.file}\0${current}`).slice(0,24)}`;this.rollbacks.set(token,{file:plan.file,content:current});this.writeAtomic(plan.file,next);return{changeHash:sha(next),rollbackToken:token,resultSha256:sha(next)};}
  rollback(token){const saved=this.rollbacks.get(token);if(!saved)return{restored:false};this.writeAtomic(saved.file,saved.content);this.rollbacks.delete(token);return{restored:true,resultSha256:sha(saved.content)};}
}
class CodeAssistiveSecurityOrganism{
  constructor({projectId,workspace,verifiers={},learningRecorder=async()=>{},reporter=async()=>{},organs={}}){this.projectId=projectId;this.workspace=workspace;this.verifiers=verifiers;this.learningRecorder=learningRecorder;this.reporter=reporter;this.regressions=[];this.organs={detector:true,planner:true,executor:true,verifier:true,learningWorker:true,securityGate:true,...organs};}
  health(){const states={};for(const [organ,value] of Object.entries(this.organs))states[organ]=typeof value==='string'?value:(value?'healthy':'blocked');const values=Object.values(states);const blocked=values.filter((state)=>state==='blocked').length;const state=values.includes('inhibited')||blocked>1?'inhibited':(blocked||values.includes('degraded')?'degraded':'healthy');return{projectId:this.projectId,state,organs:states,blocked};}
  setOrgan(organ,status){if(!(organ in this.organs))throw new Error(`Unknown organ ${organ}.`);const normalized=typeof status==='boolean'?(status?'healthy':'blocked'):status;if(!['healthy','degraded','blocked','inhibited'].includes(normalized))throw new Error(`Invalid organ status ${status}.`);this.organs[organ]=normalized;return this.health();}
  scan(dependencyManifest={}){const health=this.health();if(health.organs.detector!=='healthy'||health.organs.securityGate!=='healthy')return{...health,findings:[],context:null};return{...health,...buildThreatContext(this.workspace.snapshot(),dependencyManifest)};}
  plan(finding,{before,after,dependencies=[]}){if(this.health().organs.planner!=='healthy')throw new Error('Planner organ is unavailable.');if(!finding||sha(this.workspace.read(finding.file))!==finding.baseSha256)throw new Error('Finding base is stale.');if(typeof before!=='string'||!before||typeof after!=='string'||before===after)throw new Error('A bounded non-empty replacement is required.');const boundDependencies=[...new Set(dependencies)].sort().map((file)=>({file,sha256:sha(this.workspace.read(file))}));return{boundary:finding.boundary,file:finding.file,baseSha256:finding.baseSha256,before,after,reversibleChange:{beforeSha256:sha(before),afterSha256:sha(after)},rollbackPlan:'restore exact base content',dependencies:boundDependencies};}
  async repair(finding,plan){const health=this.health();const missing=Object.entries(health.organs).filter(([,state])=>state!=='healthy').map(([organ,state])=>({organ,state}));if(missing.length)return{state:'inhibited',missing,health};const verify=this.verifiers[finding.language];if(typeof verify!=='function')return{state:'blocked',reason:`No independent verifier for ${finding.language}.`,health:this.health()};const feedback=async(record,evidence)=>{const candidate={classification:'Insufficient Evidence',promotable:false,projectId:this.projectId,kind:'verified-code-outcome',record,evidenceHash:sha(JSON.stringify(evidence))};await this.learningRecorder(candidate);if(record.state==='verified')this.regressions.push({findingKind:finding.kind,language:finding.language,boundary:finding.boundary,resultHash:evidence.applied.resultSha256});};const actuator=new ProductionWorkflowActuator({projectId:this.projectId,actuatorId:`${finding.language}-security-repair`,detector:{id:`${finding.language}-detector`,run:async()=>({finding,safeToAct:true})},planner:{id:`${finding.language}-planner`,run:async()=>plan},executor:{id:`${finding.language}-executor`,run:async()=>this.workspace.apply(plan)},verifier:{id:`${finding.language}-independent-verifier`,run:async(input)=>({passed:await verify({file:finding.file,content:this.workspace.read(finding.file),finding,plan,input}),boundary:finding.boundary})},rollback:{id:`${finding.language}-rollback`,run:async({applied})=>this.workspace.rollback(applied.rollbackToken)},feedback,report:this.reporter});const result=await actuator.run({projectId:this.projectId,boundary:finding.boundary,changeBaseSha256:finding.baseSha256,dependencies:plan.dependencies});return{...result,health:this.health(),regressionCount:this.regressions.length};}
}
module.exports={LANGUAGE_PROFILES,languageFor,profileFor,buildThreatContext,InMemoryCodeWorkspace,FileSystemCodeWorkspace,CodeAssistiveSecurityOrganism};
