const fs = require('node:fs');
const path = require('node:path');
const { WORKLOAD_FIELDS } = require('./config');

// Keeps two parts of README.md from silently drifting out of sync with the
// code and workflow they document. Each generated block sits between its own
// pair of markers; `npm run docs:sync` rewrites the block, `npm run
// docs:check` (wired into Self-Test) fails if a rewrite would change anything.
const README_PATH = 'README.md';

// 1. The "Exactly what it does" step list, generated from the reusable
// workflow itself. Every named step in the-crucible.yml becomes one line, in
// the exact order GitHub Actions runs them. A handful of purely mechanical
// setup steps (checking out repositories, installing Node) add nothing a
// reader needs and are skipped.
const WORKFLOW_PATH = path.join('.github', 'workflows', 'the-crucible.yml');
const MARKER_START = '<!-- CRUCIBLE_WORKFLOW_STEPS:START (generated by `npm run docs:sync` - do not edit by hand) -->';
const MARKER_END = '<!-- CRUCIBLE_WORKFLOW_STEPS:END -->';
const SKIPPED_STEP_NAMES = new Set(['Check out the caller repository', 'Check out the pinned Crucible engine']);

function extractStepNames(workflowText) {
  const names = [];
  for (const line of workflowText.split(/\r?\n/)) {
    const match = /^\s*-\s*name:\s*(.+?)\s*$/.exec(line);
    if (!match) continue;
    const name = match[1].replace(/^['"]|['"]$/g, '');
    if (!SKIPPED_STEP_NAMES.has(name)) names.push(name);
  }
  return names;
}

function generatedBlock(root) {
  const workflowText = fs.readFileSync(path.join(root, WORKFLOW_PATH), 'utf8');
  const steps = extractStepNames(workflowText);
  const lines = [MARKER_START, ...steps.map((name, index) => `${index + 1}. ${name}.`), MARKER_END];
  return lines.join('\n');
}

// 2. The `### workload` field list, generated from src/config.js's
// WORKLOAD_FIELDS - the same array that validates and bounds these settings -
// so a field's default or bounds can never say one thing in code and another
// in the README (exactly the kind of drift that required a manual doc fix
// when workload.heartbeatSeconds was added).
const WORKLOAD_MARKER_START = '<!-- CRUCIBLE_WORKLOAD_FIELDS:START (generated by `npm run docs:sync` - do not edit by hand) -->';
const WORKLOAD_MARKER_END = '<!-- CRUCIBLE_WORKLOAD_FIELDS:END -->';

function generatedWorkloadBlock() {
  const lines = WORKLOAD_FIELDS.map((field) => `- \`${field.key}\`: ${field.description}, from ${field.minimum} through ${field.maximum}. Default: ${field.fallback}.`);
  return [WORKLOAD_MARKER_START, ...lines, WORKLOAD_MARKER_END].join('\n');
}

const SECTIONS = [
  { label: 'workflow-steps', markerStart: MARKER_START, markerEnd: MARKER_END, generate: generatedBlock },
  { label: 'workload field', markerStart: WORKLOAD_MARKER_START, markerEnd: WORKLOAD_MARKER_END, generate: () => generatedWorkloadBlock() },
];

function findBlock(text, markerStart, markerEnd) {
  const start = text.indexOf(markerStart);
  const end = text.indexOf(markerEnd);
  if (start === -1 || end === -1) return null;
  return text.slice(start, end + markerEnd.length);
}

// Windows runners check out text files with CRLF line endings, while this
// module always generates LF. Compare (and decide whether a rewrite is
// needed) after normalizing both sides, so a real content difference is the
// only thing that ever fails the check - not which OS checked the repo out.
function normalizeNewlines(text) {
  return text.replace(/\r\n/g, '\n');
}

function auditDocSync(root) {
  const readmeText = fs.readFileSync(path.join(root, README_PATH), 'utf8');
  const findings = [];
  for (const section of SECTIONS) {
    const existing = findBlock(readmeText, section.markerStart, section.markerEnd);
    if (existing === null) {
      findings.push({ type: `README.md is missing the generated ${section.label} markers`, detail: `Expected "${section.markerStart}" and "${section.markerEnd}".` });
      continue;
    }
    const expected = section.generate(root);
    if (normalizeNewlines(existing) !== normalizeNewlines(expected)) {
      findings.push({ type: `README.md ${section.label} list is out of date`, detail: `The generated ${section.label} block in README.md no longer matches its source.` });
    }
  }
  return { inSync: findings.length === 0, findings };
}

function syncReadme(root) {
  const readmePath = path.join(root, README_PATH);
  let readmeText = fs.readFileSync(readmePath, 'utf8');
  let changed = false;
  for (const section of SECTIONS) {
    const existing = findBlock(readmeText, section.markerStart, section.markerEnd);
    if (existing === null) throw new Error(`README.md is missing the generated ${section.label} markers ("${section.markerStart}" / "${section.markerEnd}"). Add them once by hand around the list, then rerun this.`);
    const expected = section.generate(root);
    if (normalizeNewlines(existing) !== normalizeNewlines(expected)) {
      readmeText = readmeText.replace(existing, expected);
      changed = true;
    }
  }
  if (changed) fs.writeFileSync(readmePath, readmeText, 'utf8');
  return { changed };
}

module.exports = { MARKER_START, MARKER_END, WORKLOAD_MARKER_START, WORKLOAD_MARKER_END, extractStepNames, generatedBlock, generatedWorkloadBlock, auditDocSync, syncReadme };
