const fs = require('node:fs');
const path = require('node:path');

// Keeps README.md's "Exactly what it does" step list from silently drifting
// out of sync with the reusable workflow it documents. Every named step in
// the-crucible.yml becomes one line, in the exact order GitHub Actions runs
// them, between two markers in README.md. A handful of purely mechanical
// setup steps (checking out repositories, installing Node) add nothing a
// reader needs and are skipped.
const WORKFLOW_PATH = path.join('.github', 'workflows', 'the-crucible.yml');
const README_PATH = 'README.md';
const MARKER_START = '<!-- CRUCIBLE_WORKFLOW_STEPS:START (generated by `npm run docs:sync` - do not edit by hand) -->';
const MARKER_END = '<!-- CRUCIBLE_WORKFLOW_STEPS:END -->';
const SKIPPED_STEP_NAMES = new Set(['Check out the caller repository', 'Check out the pinned Crucible engine']);

function extractStepNames(workflowText) {
  const names = [];
  for (const line of workflowText.split(/\r?\n/)) {
    const match = /^\s*-\s*name:\s*(.+?)\s*$/.exec(line);
    if (!match) continue;
    const name = match[1].replace(/^['"]|['"]$/g, '');
    if (!SKIPPED_STEP_NAMES.has(name)) names.push(name);
  }
  return names;
}

function generatedBlock(root) {
  const workflowText = fs.readFileSync(path.join(root, WORKFLOW_PATH), 'utf8');
  const steps = extractStepNames(workflowText);
  const lines = [MARKER_START, ...steps.map((name, index) => `${index + 1}. ${name}.`), MARKER_END];
  return lines.join('\n');
}

function currentBlock(readmeText) {
  const start = readmeText.indexOf(MARKER_START);
  const end = readmeText.indexOf(MARKER_END);
  if (start === -1 || end === -1) return null;
  return readmeText.slice(start, end + MARKER_END.length);
}

// Windows runners check out text files with CRLF line endings, while this
// module always generates LF. Compare (and decide whether a rewrite is
// needed) after normalizing both sides, so a real content difference is the
// only thing that ever fails the check - not which OS checked the repo out.
function normalizeNewlines(text) {
  return text.replace(/\r\n/g, '\n');
}

function auditDocSync(root) {
  const readmeText = fs.readFileSync(path.join(root, README_PATH), 'utf8');
  const existing = currentBlock(readmeText);
  if (existing === null) {
    return { inSync: false, findings: [{ type: 'README.md is missing the generated workflow-steps markers', detail: `Expected "${MARKER_START}" and "${MARKER_END}".` }] };
  }
  const expected = generatedBlock(root);
  if (normalizeNewlines(existing) === normalizeNewlines(expected)) return { inSync: true, findings: [] };
  return { inSync: false, findings: [{ type: 'README.md workflow-steps list is out of date', detail: 'The named steps in .github/workflows/the-crucible.yml no longer match the generated block in README.md.' }] };
}

function syncReadme(root) {
  const readmePath = path.join(root, README_PATH);
  const readmeText = fs.readFileSync(readmePath, 'utf8');
  const existing = currentBlock(readmeText);
  if (existing === null) throw new Error(`README.md is missing the generated workflow-steps markers ("${MARKER_START}" / "${MARKER_END}"). Add them once by hand around the step list, then rerun this.`);
  const expected = generatedBlock(root);
  if (normalizeNewlines(existing) === normalizeNewlines(expected)) return { changed: false };
  fs.writeFileSync(readmePath, readmeText.replace(existing, expected), 'utf8');
  return { changed: true };
}

module.exports = { MARKER_START, MARKER_END, extractStepNames, generatedBlock, auditDocSync, syncReadme };
