const path=require('node:path');

const ALLOWED_OPERATIONS=Object.freeze(['project-read','project-bounded-write','ephemeral-temp-write','github-hosted-analysis','governed-cross-repository']);
const FORBIDDEN_OPERATIONS=Object.freeze(['host-discovery','profile-write','startup-install','scheduled-task-install','service-install','host-tool-install','credential-read','unrelated-file-read','github-repository-discovery','github-organization-discovery','github-secret-enumeration','runner-persistence','local-gpu']);
const CROSS_REPOSITORY_PURPOSES=Object.freeze(['read-analysis','issue-report','governance-injection','learning-transport']);
function within(root,target){const base=path.resolve(root),resolved=path.resolve(target);return resolved===base||resolved.startsWith(`${base}${path.sep}`);}
class HostIsolationPolicy{
  constructor({projectRoot,tempRoot,githubActions=process.env.GITHUB_ACTIONS==='true',gpuGate=null,optedInRepositories=[]}){if(!projectRoot||!tempRoot)throw new Error('Host isolation requires explicit project and temporary roots.');this.projectRoot=path.resolve(projectRoot);this.tempRoot=path.resolve(tempRoot);this.githubActions=githubActions;this.gpuGate=gpuGate;this.optedInRepositories=new Set(optedInRepositories);}
  authorize({operation,target=null,workloadSha256=null,repository=null,purpose=null,injectionVerified=false}){if(FORBIDDEN_OPERATIONS.includes(operation)){if(operation==='local-gpu'&&this.gpuGate)return this.gpuGate.assertAllowed(workloadSha256);throw new Error(`Host assimilation operation is forbidden: ${operation}.`);}if(!ALLOWED_OPERATIONS.includes(operation))throw new Error('Unknown host operation is denied.');if(operation==='github-hosted-analysis'&&!this.githubActions)throw new Error('Native hosted analysis requires an ephemeral GitHub Actions runner.');if(operation==='governed-cross-repository'){const optedIn=this.optedInRepositories.has(repository)||injectionVerified===true;if(!optedIn||!CROSS_REPOSITORY_PURPOSES.includes(purpose))throw new Error('Cross-repository operation requires exact Crucible opt-in and governed purpose.');return{authorized:true,operation,repository,purpose,optedIn:true,hostAssimilation:false};}if(operation==='project-read'||operation==='project-bounded-write'){if(!target||!within(this.projectRoot,target))throw new Error('Operation escapes the explicitly opened project.');}if(operation==='ephemeral-temp-write'){if(!target||!within(this.tempRoot,target))throw new Error('Temporary operation escapes the per-run root.');}return{authorized:true,operation,target:target?path.resolve(target):null,hostAssimilation:false};}
}
module.exports={ALLOWED_OPERATIONS,FORBIDDEN_OPERATIONS,CROSS_REPOSITORY_PURPOSES,within,HostIsolationPolicy};
