'use strict';

const PROFILES=Object.freeze({
  javascript:{independentVariable:'the single JavaScript operation, input, or implementation change under test',dependentVariable:'exact return value, thrown error, reference identity, mutation, and observable side effects',controlledVariables:['Node.js version and flags','package-lock dependency graph','fixture inputs and module mode','operating system where behavior is platform-sensitive'],measurementMethod:'deterministic Node.js assertions plus exit code and content-addressed stdout/stderr'},
  typescript:{independentVariable:'the single TypeScript source/type/configuration change under test',dependentVariable:'compiler diagnostics, emitted JavaScript, runtime assertion, and source-map identity',controlledVariables:['TypeScript compiler version','tsconfig options','locked declarations and dependencies','runtime and fixture inputs'],measurementMethod:'TypeScript compiler API diagnostics and deterministic emitted/runtime assertions'},
  python:{independentVariable:'the single Python expression, input, dependency, or implementation change under test',dependentVariable:'return value, exception type/message, mutation, output, and process exit state',controlledVariables:['Python implementation and version','locked environment and dependency versions','fixture inputs and locale','operating system where relevant'],measurementMethod:'isolated Python assertions with captured exit status and content-addressed output'},
  django:{independentVariable:'the single Django request, model, setting, middleware, or view change under test',dependentVariable:'response/status, database mutation, authorization result, template output, and emitted security signal',controlledVariables:['Python and Django versions','settings and middleware order','database schema/fixture transaction','authenticated principal and request'],measurementMethod:'isolated Django test client and transactional database assertions'},
  java:{independentVariable:'the single Java input, call, compiler option, or implementation change under test',dependentVariable:'compiler diagnostics, return/exception, state mutation, bytecode/runtime output, and exit status',controlledVariables:['JDK vendor/version and flags','classpath and locked dependencies','fixture inputs','operating system where relevant'],measurementMethod:'javac diagnostics plus isolated JVM assertions and content-addressed output'},
  c:{independentVariable:'the single C input, macro, compiler flag, or source change under test',dependentVariable:'compiler diagnostics, return value, memory/state effect, sanitizer finding, and process exit status',controlledVariables:['compiler/version and target triple','optimization and sanitizer flags','linked libraries','fixture inputs and architecture'],measurementMethod:'compiler diagnostics, deterministic native assertions, and sanitizer/exit evidence'},
  'c++':{independentVariable:'the single C++ input, template/configuration, compiler flag, or source change under test',dependentVariable:'compiler diagnostics, return/exception, object lifetime/state effect, sanitizer finding, and process exit status',controlledVariables:['compiler/version and language standard','optimization/sanitizer flags','ABI and linked libraries','fixture inputs and architecture'],measurementMethod:'compiler diagnostics, deterministic native assertions, and sanitizer/exit evidence'},
  'c#':{independentVariable:'the single C# input, project option, API call, or source change under test',dependentVariable:'Roslyn diagnostics, return/exception, state effect, emitted assembly behavior, and exit status',controlledVariables:['.NET SDK/runtime and Roslyn versions','target framework and project properties','NuGet lock graph','fixture inputs and operating system'],measurementMethod:'Roslyn diagnostics plus isolated dotnet assertions and content-addressed output'},
  powershell:{independentVariable:'the single PowerShell command, parameter, input object, or script change under test',dependentVariable:'success/error streams, object output, state mutation, exit code, and parser diagnostics',controlledVariables:['PowerShell edition/version','execution policy and language mode','module versions','fixture filesystem/environment'],measurementMethod:'native parser AST checks and isolated Pester-style stream/state assertions'},
  shell:{independentVariable:'the single shell command, argument, input stream, or script change under test',dependentVariable:'stdout/stderr bytes, exit status, filesystem mutation, and ShellCheck/parser finding',controlledVariables:['shell implementation/version','locale and environment','working directory and fixture files','external command versions'],measurementMethod:'Tree-sitter/ShellCheck findings plus isolated process and filesystem assertions'},
  html:{independentVariable:'the single HTML element, attribute, input document, or markup change under test',dependentVariable:'parsed DOM tree, conformance diagnostics, accessible name/role, and serialized structure',controlledVariables:['HTML parser/version','document mode and encoding','fixture markup','linked-resource absence or fixed hashes'],measurementMethod:'standards-aware parser tree and deterministic conformance/accessibility assertions'},
  css:{independentVariable:'the single CSS rule, selector, declaration, or fixture-state change under test',dependentVariable:'parser diagnostics, cascade winner, computed value, and bounded layout/style result',controlledVariables:['CSS parser/browser engine version','viewport and media state','DOM fixture','stylesheet order and origin'],measurementMethod:'standards-aware CSS AST plus deterministic cascade/computed-style assertions'},
  react:{independentVariable:'the single React prop, state transition, event, component, or implementation change under test',dependentVariable:'rendered tree, dispatched effect, state transition, accessibility output, and warning/error',controlledVariables:['React/runtime versions','renderer and strict-mode setting','component fixture and initial state','scheduler/timer configuration'],measurementMethod:'deterministic renderer/DOM assertions with controlled events, effects, and timers'},
  'react-native':{independentVariable:'the single React Native prop, state transition, event, native boundary, or component change under test',dependentVariable:'rendered native tree, bridge call, state/effect transition, accessibility output, and warning/error',controlledVariables:['React Native/runtime versions','platform and mocked native modules','component fixture and initial state','scheduler/timer configuration'],measurementMethod:'deterministic native-renderer assertions with controlled bridge, events, effects, and timers'},
  json:{independentVariable:'the single JSON token, value, schema constraint, or transformation change under test',dependentVariable:'parse result, schema diagnostics, canonical value, and round-trip serialization',controlledVariables:['JSON parser/schema version','encoding','schema and fixture document','number/string normalization rules'],measurementMethod:'strict parser and schema assertions plus byte-bounded round-trip comparison'},
});
function variablesForLanguage(language,candidate){const key=String(language||'').toLowerCase();const profile=PROFILES[key];if(!profile)throw new Error(`No governed hypothesis-variable profile exists for language ${language||'<missing>'}.`);return{...profile,controlCondition:`the same ${key} fixture without the tested intervention`,positiveControl:`a known ${key} fixture must produce its documented bounded response`,negativeControl:`an irrelevant or no-operation ${key} change must not produce the claimed effect`,expectedOutcome:`the declared measurement supports exactly: ${candidate.claim}`,falsificationCriterion:'the expected measurement is absent, a control behaves unexpectedly, a confounder explains the result, or any observation exceeds the declared boundary',fixtureBoundary:candidate.claimBoundary,confounders:[`${key} runtime/compiler/parser version`,'fixture or environment behavior','dependency or toolchain behavior','shared upstream source error']};}
module.exports={PROFILES,variablesForLanguage};
