const crypto=require('node:crypto');const fs=require('node:fs');const path=require('node:path');
const sha=(value)=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
const EXTENSIONS=Object.freeze({'.json':'json','.js':'javascript','.mjs':'javascript','.cjs':'javascript','.jsx':'react','.ts':'typescript','.tsx':'react','.py':'python','.java':'java','.c':'c','.h':'c','.cc':'cpp','.cpp':'cpp','.cxx':'cpp','.hpp':'cpp','.cs':'csharp','.ps1':'powershell','.psm1':'powershell','.sh':'shell','.bash':'shell','.html':'html','.htm':'html','.css':'css'});
const BASELINE_SUFFIXES=Object.freeze(['.edu']);const ESTABLISHED_SUFFIXES=Object.freeze(['.edu','.org','.gov']);
function name(value){if(typeof value!=='string'||!/^[a-z][a-z0-9+#.-]{0,39}$/i.test(value))throw new Error('Language names must be bounded identifiers.');return value.toLowerCase();}
function host(value){const checked=String(value).trim().toLowerCase().replace(/^\.+/,'');if(!checked||checked.includes('/')||checked.includes(':')||!checked.includes('.'))throw new Error('Denylist entries must be domain names.');return checked;}
class LanguageCapabilityCatalog{
  constructor({root,projectId,now=()=>new Date().toISOString()}){this.root=path.resolve(root);this.projectId=projectId;this.now=now;this.file=path.join(this.root,'language-capabilities.json');fs.mkdirSync(this.root,{recursive:true});}
  empty(){return{schemaVersion:1,projectId:this.projectId,revision:0,languages:[],denylist:[],audit:[]};}
  read(){if(!fs.existsSync(this.file))return this.empty();const envelope=JSON.parse(fs.readFileSync(this.file,'utf8'));if(envelope.sha256!==sha(envelope.payload)||envelope.payload?.projectId!==this.projectId)throw new Error('Language catalog integrity or project binding failed.');return structuredClone(envelope.payload);}
  write(state){state.revision+=1;const envelope={payload:state,sha256:sha(state)};const temporary=`${this.file}.${process.pid}.${crypto.randomUUID()}.tmp`;fs.writeFileSync(temporary,`${JSON.stringify(envelope,null,2)}\n`,{flag:'wx',mode:0o600});fs.renameSync(temporary,this.file);}
  registerCapability({id,extensions=[]}){const checked=name(id);if(!Array.isArray(extensions)||!extensions.length||extensions.some((item)=>typeof item!=='string'||!/^\.[a-z0-9]+$/i.test(item)))throw new Error('Language capability extensions are required.');const state=this.read();let entry=state.languages.find((item)=>item.id===checked);if(!entry){const at=this.now();entry={id:checked,state:'clean-slate',discoveredAt:at,baselineVerifiedAt:null,verifiedKnowledgeIds:[],researchSuffixes:[...BASELINE_SUFFIXES],researchTopics:[`${checked} language specification`,`${checked} secure coding`],sourceFiles:[],extensions:[...new Set(extensions.map((item)=>item.toLowerCase()))].sort()};state.languages.push(entry);state.audit.push({at,action:'language-capability-registered',language:checked,scope:'edu-only'});this.write(state);return{added:true,language:checked};}const merged=[...new Set([...(entry.extensions||[]),...extensions.map((item)=>item.toLowerCase())])].sort();if(JSON.stringify(merged)!==JSON.stringify(entry.extensions||[])){entry.extensions=merged;state.audit.push({at:this.now(),action:'language-capability-expanded',language:checked});this.write(state);}return{added:false,language:checked};}
  projectFiles({projectRoot,maxFiles=10000}={}){const root=path.resolve(projectRoot||'.');if(!Number.isInteger(maxFiles)||maxFiles<1||maxFiles>50000)throw new Error('Project language scan file bound is invalid.');const excluded=new Set(['.git','node_modules','dist','build','coverage','.the-crucible-runtime']);const files=[];const walk=(directory)=>{for(const entry of fs.readdirSync(directory,{withFileTypes:true})){if(excluded.has(entry.name))continue;const absolute=path.join(directory,entry.name);if(entry.isDirectory()){if(entry.name.startsWith('.'))continue;walk(absolute);}else if(entry.isFile()&&EXTENSIONS[path.extname(entry.name).toLowerCase()]){files.push(path.relative(root,absolute));if(files.length>maxFiles)throw new Error('Project language scan exceeded its file bound.');}}};walk(root);return files.sort();}
  discover(files){const state=this.read();const before=JSON.stringify(state.languages);const existing=new Set(state.languages.map((item)=>item.id));const added=[];const identify=(file)=>{let language=EXTENSIONS[path.extname(file).toLowerCase()]||state.languages.find((item)=>(item.extensions||[]).includes(path.extname(file).toLowerCase()))?.id;if(language==='python'&&/(?:^|[/\\])django[/\\]/i.test(file))language='django';return language;};for(const file of files){const language=identify(file);if(!language||existing.has(language))continue;const at=this.now();const entry={id:name(language),state:'clean-slate',discoveredAt:at,baselineVerifiedAt:null,verifiedKnowledgeIds:[],researchSuffixes:[...BASELINE_SUFFIXES],researchTopics:[`${language} language specification`,`${language} secure coding`],sourceFiles:[file],extensions:[]};state.languages.push(entry);state.audit.push({at,action:'language-discovered',language,scope:'edu-only'});existing.add(language);added.push(language);}for(const entry of state.languages)entry.sourceFiles=[...new Set([...entry.sourceFiles,...files.filter((file)=>identify(file)===entry.id)])].sort();state.languages.sort((a,b)=>a.id.localeCompare(b.id));if(before!==JSON.stringify(state.languages))this.write(state);return{added,settingsLanguages:state.languages.map((item)=>item.id),researchTopics:state.languages.flatMap((item)=>item.researchTopics)};}
  establish(language,verifiedKnowledgeIds){const checked=name(language);if(!Array.isArray(verifiedKnowledgeIds)||!verifiedKnowledgeIds.length||verifiedKnowledgeIds.some((item)=>typeof item!=='string'||!item))throw new Error('Verified baseline knowledge IDs are required.');const state=this.read();const entry=state.languages.find((item)=>item.id===checked);if(!entry)throw new Error('Language is not registered.');entry.state='established';entry.baselineVerifiedAt=this.now();entry.verifiedKnowledgeIds=[...new Set([...entry.verifiedKnowledgeIds,...verifiedKnowledgeIds])].sort();entry.researchSuffixes=[...ESTABLISHED_SUFFIXES];state.audit.push({at:this.now(),action:'baseline-established',language:checked,knowledgeIds:[...verifiedKnowledgeIds]});this.write(state);return structuredClone(entry);}
  addDeniedDomain(domain,{reason,source}){if(typeof reason!=='string'||!reason||typeof source!=='string'||!source)throw new Error('Denylist growth requires reason and source.');const checked=host(domain);const state=this.read();if(!state.denylist.some((item)=>item.domain===checked)){state.denylist.push({domain:checked,reason,source,addedAt:this.now()});state.denylist.sort((a,b)=>a.domain.localeCompare(b.domain));state.audit.push({at:this.now(),action:'domain-denied',domain:checked,reason,source});this.write(state);return{added:true,domain:checked};}return{added:false,domain:checked};}
  settings(){const state=this.read();return{languages:state.languages.map((item)=>item.id),denylist:state.denylist.map((item)=>item.domain)};}
  researchScope(topic){const state=this.read();const entry=state.languages.find((item)=>item.researchTopics.includes(topic));if(!entry)throw new Error('Research topic is not governed by the language catalog.');return{language:entry.id,state:entry.state,trustedSuffixes:[...entry.researchSuffixes],deniedDomains:state.denylist.map((item)=>item.domain)};}
}
class OrganismResearchController{
  constructor({catalog,researchFactory}){if(!catalog||typeof researchFactory!=='function')throw new Error('Catalog and research factory are required.');this.catalog=catalog;this.researchFactory=researchFactory;this.enabled=true;this.research=null;}
  synchronize({files=null,projectRoot=null,capabilities=[]}){for(const capability of capabilities)this.catalog.registerCapability(capability);const boundedFiles=files||this.catalog.projectFiles({projectRoot});const discovered=this.catalog.discover(boundedFiles);this.research=this.researchFactory(discovered.researchTopics,(topic)=>this.catalog.researchScope(topic));return{...discovered,settings:this.catalog.settings(),scannedFiles:boundedFiles.length};}
  inhibit(){this.enabled=false;return{state:'inhibited'};} recover(){this.enabled=true;return{state:'healthy'};}
  quarantineDomain(domain,evidence){return this.catalog.addDeniedDomain(domain,evidence);}
  async runDue(at){if(!this.enabled)return[{state:'inhibited',reason:'Research organ is inhibited.'}];if(!this.research)throw new Error('Research organ must synchronize before execution.');return this.research.runDue(at);}
}
module.exports={EXTENSIONS,BASELINE_SUFFIXES,ESTABLISHED_SUFFIXES,LanguageCapabilityCatalog,OrganismResearchController};
