const crypto=require('node:crypto');const fs=require('node:fs');const path=require('node:path');
function hash(value){return crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');}
const ROUTES=Object.freeze({candidate:'comparison-and-critical-review',hypothesis:'controlled-experiment',experimented:'causal-isolation-review','causally-proven':'independent-verification','independently-verified':'contradiction-analysis',quarantined:'quarantine-resolution',rejected:'stop',verified:'active-knowledge'});
const PRIORITY=Object.freeze({quarantined:100,experimented:90,'causally-proven':85,'independently-verified':80,hypothesis:75,candidate:60,rejected:0,verified:0});
class LearningOrchestratorLedger{
  constructor({root,projectId}){this.root=path.resolve(root);this.projectId=projectId;this.file=path.join(this.root,'learning-orchestrator.json');fs.mkdirSync(this.root,{recursive:true});}
  read(){if(!fs.existsSync(this.file))return{schemaVersion:1,projectId:this.projectId,events:[]};const envelope=JSON.parse(fs.readFileSync(this.file,'utf8'));if(envelope?.sha256!==hash(envelope.payload)||envelope.payload?.projectId!==this.projectId||!Array.isArray(envelope.payload.events))throw new Error('Learning orchestrator ledger integrity or project binding failed.');return structuredClone(envelope.payload);}
  record(event){if(event?.projectId!==this.projectId||event?.promotionAuthorized!==false||event?.proofStageSatisfied!==false)throw new Error('Orchestrator events are coordination-only and cannot prove or promote.');const state=this.read();state.events.push(structuredClone(event));const envelope={payload:state,sha256:hash(state)};const temporary=`${this.file}.${process.pid}.${crypto.randomUUID()}.tmp`;fs.writeFileSync(temporary,`${JSON.stringify(envelope,null,2)}\n`,{flag:'wx',mode:0o600});fs.renameSync(temporary,this.file);return structuredClone(event);}
}
class CrucibleLearningOrchestrator{
  constructor({store,ledger,extractor=null,evaluator=null,experienceRecorder=null,now=()=>new Date().toISOString()}){if(!store?.read||!store?.retrieve||!store.projectId||ledger?.projectId!==store.projectId)throw new Error('Orchestrator requires same-project durable learning and audit custody.');this.store=store;this.ledger=ledger;this.extractor=extractor;this.evaluator=evaluator;this.experienceRecorder=experienceRecorder;this.now=now;}
  attention(limit=25){if(!Number.isInteger(limit)||limit<1||limit>100)throw new Error('Attention limit must be between 1 and 100.');return this.store.read().candidateRecords.map((record)=>({candidateId:record.candidate.id,state:record.state,classification:record.candidate.classification,priority:(record.candidate.classification==='Crucible Issue'?110:PRIORITY[record.state]??0),route:ROUTES[record.state]||'inhibit-unknown-state',claimBoundary:record.candidate.claimBoundary})).filter((item)=>item.priority>0).sort((a,b)=>b.priority-a.priority||a.candidateId.localeCompare(b.candidateId)).slice(0,limit);}
  plan(limit=25){return this.attention(limit).map((item,index)=>({...item,order:index+1,dependencies:item.route==='independent-verification'?['controlled proof','causal isolation']:item.route==='controlled-experiment'?['falsifiable hypothesis','critical review','reasoning plan']:[]}));}
  memory(boundary){if(typeof boundary!=='string'||!boundary.trim())throw new Error('Exact knowledge boundary is required.');return this.store.retrieve({boundary});}
  feedback(experiences){if(!this.experienceRecorder?.record)throw new Error('Suite feedback recorder is not configured.');return this.experienceRecorder.record(experiences);}
  inhibit({projectId,action,classification,boundary}){const reasons=[];if(projectId!==this.store.projectId)reasons.push('cross-project');if(action==='promote'||action==='verify')reasons.push('orchestrator-cannot-prove-or-promote');if(classification==='Crucible Issue')reasons.push('contradiction-quarantine');if(typeof boundary!=='string'||!boundary.trim())reasons.push('missing-boundary');return{allowed:reasons.length===0,reasons};}
  async coordinate({runExtraction=false,evaluations=[]}={}){if(!Array.isArray(evaluations)||evaluations.length>25)throw new Error('Evaluations must be a bounded array.');const extraction=runExtraction?(this.extractor?.run?this.extractor.run():(()=>{throw new Error('Extraction worker is not configured.');})()):[];const results=[];for(const request of evaluations){const inhibition=this.inhibit({projectId:request.projectId,action:'evaluate',classification:request.classification||'Insufficient Evidence',boundary:request.boundary});if(!inhibition.allowed){results.push({request,state:'inhibited',reasons:inhibition.reasons});continue;}if(!this.evaluator?.process)throw new Error('Controlled evaluator is not configured.');results.push(await this.evaluator.process(request));}const event={schemaVersion:1,projectId:this.store.projectId,at:this.now(),type:'coordination-cycle',extracted:extraction.length,evaluations:results.length,inhibited:results.filter((item)=>item.state==='inhibited').length,proofStageSatisfied:false,promotionAuthorized:false};this.ledger.record(event);return{extraction,results,event,metacognition:this.metacognition()};}
  metacognition(){const payload=this.store.read();const states=Object.fromEntries([...new Set(payload.candidateRecords.map((item)=>item.state))].sort().map((state)=>[state,payload.candidateRecords.filter((item)=>item.state===state).length]));return{projectId:this.store.projectId,known:{activeVerifiedKnowledge:payload.knowledgeVersions.filter((item)=>item.status==='active').length},uncertain:{candidateStates:states},blocked:{quarantined:states.quarantined||0,rejected:states.rejected||0},awaitingVerification:(states.candidate||0)+(states.hypothesis||0)+(states.experimented||0)+(states['causally-proven']||0),orchestratorIsProofSource:false,reportedAt:this.now()};}
}
module.exports={ROUTES,PRIORITY,LearningOrchestratorLedger,CrucibleLearningOrchestrator};
