'use strict';const crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');const {CardiopulmonaryCirculation}=require('./organismCirculation');
const sha=(value)=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');const terminal=new Set(['completed','inhibited','rolled-back','quarantined','rejected']);
class DurableOrganismRuntime{
  constructor({projectId,root,organs,learningStore,oversightReflex,maximumQueue=100,staleAfterMs=15*60*1000,now=()=>new Date().toISOString()}){if(!projectId||!root||!organs||!learningStore?.retrieve||!oversightReflex?.evaluate)throw new Error('Organism runtime requires project, organs, memory, and oversight reflex.');this.projectId=projectId;this.root=path.resolve(root);this.file=path.join(this.root,'organism-runtime.json');this.organs=organs;this.learningStore=learningStore;this.oversightReflex=oversightReflex;this.maximumQueue=maximumQueue;this.staleAfterMs=staleAfterMs;this.now=now;fs.mkdirSync(this.root,{recursive:true});if(!fs.existsSync(this.file))this.write({schemaVersion:1,projectId,revision:0,stopped:null,queue:[],completedKeys:[],organs:Object.fromEntries(Object.keys(organs).map((id)=>[id,{state:'healthy',dependency:null,lastSeenAt:this.now()}])),events:[]});this.read();}
  read(){const envelope=JSON.parse(fs.readFileSync(this.file,'utf8'));if(envelope.sha256!==sha(envelope.payload)||envelope.payload.projectId!==this.projectId)throw new Error('Organism runtime state is corrupt or cross-project.');return structuredClone(envelope.payload);}
  write(payload){const temp=`${this.file}.${process.pid}.${crypto.randomUUID()}.tmp`;fs.writeFileSync(temp,`${JSON.stringify({payload,sha256:sha(payload)},null,2)}\n`,{flag:'wx',mode:0o600});fs.renameSync(temp,this.file);}
  mutate(action,fn){const state=this.read(),next=fn(structuredClone(state));next.revision=state.revision+1;next.events.push({at:this.now(),action});this.write(next);return structuredClone(next);}
  stateHash(){return sha(this.read());}
  applyOversight(envelope){const decision=this.oversightReflex.evaluate(envelope);if(decision.stateSha256!==this.stateHash())throw new Error('Oversight decision does not bind the current organism state.');return this.mutate(`oversight:${decision.decision}`,(state)=>{if(decision.decision==='STOP')state.stopped=decision;else{if(!state.stopped)throw new Error('Cannot clear an organism that is not stopped.');state.stopped=null;}return state;});}
  setOrganAvailability(organId,available,dependency,authority){if(!this.organs[organId])throw new Error('Unknown organ.');const required=available?'governance+immune':'governance';if(authority!==required)throw new Error(`${required} authority is required to ${available?'recover':'inhibit'} an organ.`);return this.mutate(`organ:${organId}:${available?'recover':'unavailable'}`,(state)=>{state.organs[organId]={state:available?'healthy':'unavailable',dependency:available?null:(dependency||'unavailable dependency'),lastSeenAt:this.now()};return state;});}
  submit({id,type,sourceOrgan,targetOrgan,boundary,payload}){if(!id||!targetOrgan||!boundary)throw new Error('Bounded work identity, target, and boundary are required.');return this.mutate(`submit:${id}`,(state)=>{if(state.stopped)throw new Error('Independent oversight STOP inhibits the organism.');const key=sha({id,type,sourceOrgan,targetOrgan,boundary,payload});if(state.completedKeys.includes(key)||state.queue.some((item)=>item.key===key))return state;if(state.queue.length>=this.maximumQueue)throw new Error('Heartbeat backpressure limit reached; work is inhibited, not dropped.');state.queue.push({id,key,type,sourceOrgan,targetOrgan,boundary,payload,submittedAt:this.now(),attempts:0,state:'queued'});return state;});}
  async heartbeat(limit=25){let state=this.read();if(state.stopped)return{state:'stopped-by-independent-oversight',processed:0,health:this.health()};const due=state.queue.filter((item)=>item.state==='queued').slice(0,limit),results=[];for(const item of due){state=this.read();const organ=state.organs[item.targetOrgan];if(!organ||organ.state!=='healthy'){this.mutate(`inhibit:${item.id}`,(next)=>{const queued=next.queue.find((value)=>value.key===item.key);queued.state='inhibited';queued.reason=organ?.dependency||'missing organ';return next;});results.push({id:item.id,state:'inhibited'});continue;}const circulation=new CardiopulmonaryCirculation({projectId:this.projectId,organs:{[item.targetOrgan]:async(envelope,payload)=>this.organs[item.targetOrgan]({envelope,payload,memory:this.learningStore.retrieve({boundary:item.boundary})})},maximumSignals:this.maximumQueue,now:this.now});circulation.admit({projectId:this.projectId,type:item.type,sourceOrgan:item.sourceOrgan,targetOrgan:item.targetOrgan,boundary:item.boundary},item.payload);try{const [result]=await circulation.pump();this.mutate(`complete:${item.id}`,(next)=>{const queued=next.queue.find((value)=>value.key===item.key);queued.state='completed';queued.completedAt=this.now();next.completedKeys.push(item.key);next.organs[item.targetOrgan].lastSeenAt=this.now();return next;});results.push({id:item.id,state:result.state,output:result.output});}catch(error){this.mutate(`failure:${item.id}`,(next)=>{const queued=next.queue.find((value)=>value.key===item.key);queued.attempts++;queued.lastError=String(error.message||error);if(queued.attempts>=3){queued.state='quarantined';next.organs[item.targetOrgan]={state:'degraded',dependency:queued.lastError,lastSeenAt:this.now()};}return next;});results.push({id:item.id,state:'failed',reason:String(error.message||error)});}}
    for(const result of results)if(result.output?.signals)for(const signal of result.output.signals)this.submit(signal);return{state:'heartbeat-complete',processed:results.length,results,health:this.health()};}
  recover(){return this.mutate('homeostasis-recovery',(state)=>{for(const item of state.queue)if(['inhibited','quarantined'].includes(item.state)&&state.organs[item.targetOrgan]?.state==='healthy'){item.state='queued';item.lastError=null;}return state;});}
  health(){const state=this.read(),now=Date.parse(this.now()),organs={};for(const [id,status] of Object.entries(state.organs)){const stale=Number.isFinite(Date.parse(status.lastSeenAt))&&now-Date.parse(status.lastSeenAt)>this.staleAfterMs;organs[id]={state:status.state==='healthy'&&stale?'degraded':status.state,missingDependency:status.dependency||null,stale};}const queued=state.queue.filter((item)=>!terminal.has(item.state)).length;return{projectId:this.projectId,state:state.stopped?'inhibited':Object.values(organs).some((item)=>item.state!=='healthy')?'degraded':queued>=this.maximumQueue?'backpressure':'healthy',oversight:state.stopped?{state:'STOP',reason:state.stopped.reason}:{state:'CLEAR'},queue:{active:queued,capacity:this.maximumQueue},organs,revision:state.revision};}
}
module.exports={DurableOrganismRuntime};
