const crypto=require('node:crypto');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {execFile}=require('node:child_process');const ts=require('typescript');
const sha=(value)=>crypto.createHash('sha256').update(value).digest('hex');
const SOURCE_NAMES=new Set(['request','req','body','query','params','input','userInput','stdin']);
const SINK_NAMES=new Set(['eval','exec','execute','query','system','spawn','innerHTML','writeFile']);
function inside(root,target){const resolved=path.resolve(root,target);if(resolved!==root&&!resolved.startsWith(`${root}${path.sep}`))throw new Error('Analysis path escapes project root.');return resolved;}
function normalizedFinding(input){const required=['projectId','language','kind','file','boundary','baseSha256','toolId','toolVersion'];for(const field of required)if(typeof input[field]!=='string'||!input[field])throw new Error(`Semantic finding requires ${field}.`);if(!Number.isInteger(input.start)||!Number.isInteger(input.end)||input.start<0||input.end<=input.start)throw new Error('Semantic finding requires a valid source range.');return Object.freeze({schemaVersion:1,...input,proofStageSatisfied:false,promotionAuthorized:false});}
class SecureCompilerWorker{
  constructor({root,allowExecutables,timeoutMs=20000,maxOutputBytes=8*1024*1024}){this.root=path.resolve(root);this.allow=new Set(allowExecutables.map((item)=>path.resolve(item)));this.timeoutMs=timeoutMs;this.maxOutputBytes=maxOutputBytes;}
  run(executable,args,{cwd='.',allowExitCodes=[0],toolHome=null}={}){const resolved=path.resolve(executable);if(!this.allow.has(resolved))throw new Error('Compiler executable is not allow-listed.');const workdir=inside(this.root,cwd);const temporaryRoot=toolHome?inside(path.resolve(os.tmpdir()),toolHome):path.resolve(os.tmpdir());return new Promise((resolve,reject)=>execFile(resolved,args,{cwd:workdir,shell:false,windowsHide:true,timeout:this.timeoutMs,maxBuffer:this.maxOutputBytes,env:{PATH:path.dirname(resolved),SystemRoot:process.env.SystemRoot||'',WINDIR:process.env.WINDIR||'',TEMP:process.env.TEMP||'',TMP:process.env.TMP||'',HOME:temporaryRoot,DOTNET_CLI_HOME:temporaryRoot,DOTNET_SKIP_FIRST_TIME_EXPERIENCE:'1',DOTNET_NOLOGO:'1'}},(error,stdout,stderr)=>{const exitCode=error?.code??0;if(error&&!allowExitCodes.includes(exitCode))return reject(new Error(`Compiler worker failed closed: ${error.message}\n${String(stdout).slice(-4000)}\n${String(stderr).slice(-4000)}`));resolve({stdout,stderr,exitCode,stdoutSha256:sha(stdout),stderrSha256:sha(stderr)});}));}
}
class TypeScriptSemanticAdapter{
  constructor({projectId,root}){this.projectId=projectId;this.root=path.resolve(root);this.id='typescript-compiler-api';this.version=ts.version;}
  analyze({files,compilerOptions={}}){const absolute=files.map((file)=>inside(this.root,file));const program=ts.createProgram(absolute,{allowJs:true,checkJs:true,jsx:ts.JsxEmit.ReactJSX,noEmit:true,target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,...compilerOptions});const checker=program.getTypeChecker();const functions=new Map();const calls=[];const findings=[];const diagnostics=ts.getPreEmitDiagnostics(program).map((item)=>({code:item.code,category:ts.DiagnosticCategory[item.category],message:ts.flattenDiagnosticMessageText(item.messageText,'\n'),file:item.file?path.relative(this.root,item.file.fileName):null,start:item.start??null}));
    const functionId=(node,source)=>{const symbol=node.name?checker.getSymbolAtLocation(node.name):null;return symbol?`${path.relative(this.root,source.fileName)}#${checker.getFullyQualifiedName(symbol)}`:`${path.relative(this.root,source.fileName)}@${node.pos}`;};
    for(const source of program.getSourceFiles()){if(!absolute.includes(path.resolve(source.fileName)))continue;const relative=path.relative(this.root,source.fileName);const collect=(node)=>{if(ts.isFunctionDeclaration(node)||ts.isMethodDeclaration(node)||ts.isFunctionExpression(node)||ts.isArrowFunction(node)){const id=functionId(node,source);functions.set(id,{id,file:relative,start:node.getStart(source),end:node.end,parameters:node.parameters.map((p)=>p.name.getText(source)),sources:[],sinks:[]});}ts.forEachChild(node,collect);};collect(source);}
    for(const source of program.getSourceFiles()){if(!absolute.includes(path.resolve(source.fileName)))continue;const relative=path.relative(this.root,source.fileName);const content=source.getFullText();const stack=[];const visit=(node)=>{let entered=null;if(ts.isFunctionDeclaration(node)||ts.isMethodDeclaration(node)||ts.isFunctionExpression(node)||ts.isArrowFunction(node)){entered=functionId(node,source);stack.push(entered);}const current=stack.at(-1);if(ts.isCallExpression(node)){const expression=node.expression;const text=expression.getText(source);const short=text.split('.').at(-1);let symbol=checker.getSymbolAtLocation(ts.isPropertyAccessExpression(expression)?expression.name:expression);if(symbol&&(symbol.flags&ts.SymbolFlags.Alias))symbol=checker.getAliasedSymbol(symbol);const declaration=symbol?.valueDeclaration||symbol?.declarations?.[0];let target=null;if(declaration&&(ts.isFunctionDeclaration(declaration)||ts.isMethodDeclaration(declaration)||ts.isFunctionExpression(declaration)||ts.isArrowFunction(declaration)))target=functionId(declaration,declaration.getSourceFile());calls.push({caller:current,calleeText:text,target,file:relative,start:node.getStart(source),end:node.end});if(current&&SINK_NAMES.has(short)){functions.get(current).sinks.push({name:short,start:node.getStart(source)});findings.push(normalizedFinding({projectId:this.projectId,language:relative.endsWith('.tsx')?'react':relative.endsWith('.ts')?'typescript':'javascript',kind:'semantic-security-sink',file:relative,boundary:`${relative}:${node.getStart(source)}-${node.end}`,start:node.getStart(source),end:node.end,baseSha256:sha(content),toolId:this.id,toolVersion:this.version,callee:text}));}}if(current&&ts.isIdentifier(node)&&SOURCE_NAMES.has(node.text))functions.get(current).sources.push({name:node.text,start:node.getStart(source)});ts.forEachChild(node,visit);if(entered)stack.pop();};visit(source);}
    const paths=[];for(const [start,entry] of functions)if(entry.sources.length){const queue=[[start]];const seen=new Set([start]);while(queue.length){const chain=queue.shift();const last=chain.at(-1);if(functions.get(last)?.sinks.length){paths.push({functions:chain,source:functions.get(start).sources[0],sink:functions.get(last).sinks[0]});continue;}for(const call of calls.filter((item)=>item.caller===last&&item.target))if(!seen.has(call.target)){seen.add(call.target);queue.push([...chain,call.target]);}}}
    return{schemaVersion:1,projectId:this.projectId,adapter:{id:this.id,version:this.version},files:files.map((file)=>({file,sha256:sha(fs.readFileSync(inside(this.root,file),'utf8'))})),diagnostics,functions:[...functions.values()],calls,interproceduralPaths:paths,findings};}
  repairPlan(finding,{replacement,dependencies=[]}){if(finding.toolId!==this.id)throw new Error('Finding was not produced by this compiler adapter.');const content=fs.readFileSync(inside(this.root,finding.file),'utf8');if(sha(content)!==finding.baseSha256)throw new Error('AST repair finding is stale.');const source=ts.createSourceFile(finding.file,content,ts.ScriptTarget.Latest,true,finding.file.endsWith('x')?ts.ScriptKind.TSX:ts.ScriptKind.TS);let exact=null;const visit=(node)=>{if(node.getStart(source)===finding.start&&node.end===finding.end)exact=node;ts.forEachChild(node,visit);};visit(source);if(!exact||!ts.isCallExpression(exact))throw new Error('AST repair boundary no longer identifies a call expression.');return{file:finding.file,boundary:finding.boundary,baseSha256:finding.baseSha256,before:content.slice(finding.start,finding.end),after:replacement,dependencies,astNodeKind:ts.SyntaxKind[exact.kind],toolId:this.id,toolVersion:this.version};}
}
class PythonSemanticAdapter{
  constructor({projectId,root,pythonExecutable,nodeExecutable=process.execPath,pyrightCli=path.resolve(__dirname,'..','node_modules','pyright','index.js'),helperPath=path.resolve(__dirname,'..','scripts','pythonSemanticAnalyzer.py')}){this.projectId=projectId;this.root=path.resolve(root);this.pythonExecutable=path.resolve(pythonExecutable);this.nodeExecutable=path.resolve(nodeExecutable);this.pyrightCli=path.resolve(pyrightCli);this.helperPath=path.resolve(helperPath);this.id='python-ast-pyright';this.worker=new SecureCompilerWorker({root:this.root,allowExecutables:[this.pythonExecutable,this.nodeExecutable]});}
  async analyze({files}){for(const file of files)inside(this.root,file);const output=await this.worker.run(this.pythonExecutable,[this.helperPath,this.root,this.projectId,...files]);const parsed=JSON.parse(output.stdout);if(parsed.projectId!==this.projectId||parsed.adapter?.id!=='python-ast')throw new Error('Python semantic analyzer returned invalid project-bound output.');for(const finding of parsed.findings)normalizedFinding(finding);const typeOutput=await this.worker.run(this.nodeExecutable,[this.pyrightCli,'--outputjson',...files],{allowExitCodes:[0,1]});const typeReport=JSON.parse(typeOutput.stdout);return{...parsed,adapter:{id:this.id,version:`python-${parsed.adapter.version}/pyright-${typeReport.version}`},diagnostics:typeReport.generalDiagnostics||[],typeSummary:typeReport.summary||{},custody:{astStdoutSha256:output.stdoutSha256,astStderrSha256:output.stderrSha256,pyrightStdoutSha256:typeOutput.stdoutSha256,pyrightStderrSha256:typeOutput.stderrSha256}};}
}
class WebStandardsSemanticAdapter{
  constructor({projectId,root}){this.projectId=projectId;this.root=path.resolve(root);this.id='parse5-postcss';}
  async analyze({files}){const parse5=await import('parse5');const postcss=require('postcss');const findings=[];const edges=[];const records=[];for(const file of files){const content=fs.readFileSync(inside(this.root,file),'utf8');records.push({file,sha256:sha(content)});if(/\.html?$/i.test(file)){const document=parse5.parse(content,{sourceCodeLocationInfo:true});const visit=(node)=>{const location=node.sourceCodeLocation;if(node.tagName){for(const attribute of node.attrs||[]){const attrLocation=location?.attrs?.[attribute.name];if(attribute.name.startsWith('on')&&attrLocation)findings.push(normalizedFinding({projectId:this.projectId,language:'html',kind:'inline-event-handler',file,boundary:`${file}:${attrLocation.startOffset}-${attrLocation.endOffset}`,start:attrLocation.startOffset,end:attrLocation.endOffset,baseSha256:sha(content),toolId:this.id,toolVersion:'parse5-8',attribute:attribute.name}));if((node.tagName==='script'&&attribute.name==='src')||(node.tagName==='link'&&attribute.name==='href'))edges.push({from:file,to:attribute.value,kind:`html-${node.tagName}`});}const target=(node.attrs||[]).find((item)=>item.name==='target'&&item.value==='_blank');const rel=(node.attrs||[]).find((item)=>item.name==='rel');if(target&&!rel){const item=location?.attrs?.target;if(item)findings.push(normalizedFinding({projectId:this.projectId,language:'html',kind:'missing-opener-isolation',file,boundary:`${file}:${item.startOffset}-${item.endOffset}`,start:item.startOffset,end:item.endOffset,baseSha256:sha(content),toolId:this.id,toolVersion:'parse5-8'}));}}for(const child of node.childNodes||[])visit(child);};visit(document);}else if(/\.css$/i.test(file)){const root=postcss.parse(content,{from:file,map:false});root.walkAtRules('import',(rule)=>{const match=rule.params.match(/(?:url\()?\s*["']?([^"')\s]+)/);if(match)edges.push({from:file,to:match[1],kind:'css-import'});if(/http:\/\//i.test(rule.params))findings.push(normalizedFinding({projectId:this.projectId,language:'css',kind:'insecure-css-import',file,boundary:`${file}:${rule.source.start.offset}-${rule.source.end.offset+1}`,start:rule.source.start.offset,end:rule.source.end.offset+1,baseSha256:sha(content),toolId:this.id,toolVersion:postcss().version||'8.5.23'}));});}}
    return{schemaVersion:1,projectId:this.projectId,adapter:{id:this.id,version:'parse5-8/postcss-8.5.23'},files:records,diagnostics:[],functions:[],calls:[],interproceduralPaths:[],crossLanguageEdges:edges,findings};}
}
class ShellSemanticAdapter{
  constructor({projectId,root,shellcheckExecutable=null}){this.projectId=projectId;this.root=path.resolve(root);this.shellcheckExecutable=shellcheckExecutable?path.resolve(shellcheckExecutable):null;this.id='tree-sitter-bash-shellcheck';}
  health(){return{state:this.shellcheckExecutable&&fs.existsSync(this.shellcheckExecutable)?'healthy':'blocked',reason:this.shellcheckExecutable?'shellcheck-not-found':'shellcheck-not-configured'};}
  async analyze({files}){const Parser=require('tree-sitter');const Bash=require('tree-sitter-bash');if(this.health().state!=='healthy')throw new Error('ShellCheck is required for Shell semantic analysis.');const parser=new Parser();parser.setLanguage(Bash);const worker=new SecureCompilerWorker({root:this.root,allowExecutables:[this.shellcheckExecutable]});const findings=[];const ast=[];for(const file of files){const content=fs.readFileSync(inside(this.root,file),'utf8');const tree=parser.parse(content);ast.push({file,rootType:tree.rootNode.type,sexp:tree.rootNode.toString(),sha256:sha(content),hasError:tree.rootNode.hasError});const output=await worker.run(this.shellcheckExecutable,['-f','json',file],{allowExitCodes:[0,1]});for(const item of JSON.parse(output.stdout||'[]')){const lines=content.split(/\r?\n/);const prefix=lines.slice(0,item.line-1).reduce((sum,line)=>sum+line.length+1,0);const start=prefix+Math.max(0,item.column-1);const end=Math.max(start+1,prefix+Math.max(0,item.endColumn-1));findings.push(normalizedFinding({projectId:this.projectId,language:'shell',kind:`shellcheck-${item.code}`,file,boundary:`${file}:${start}-${end}`,start,end,baseSha256:sha(content),toolId:this.id,toolVersion:'tree-sitter-0.25.1/shellcheck',severity:item.level,message:item.message}));}}return{schemaVersion:1,projectId:this.projectId,adapter:{id:this.id,version:'tree-sitter-0.25.1'},ast,diagnostics:[],functions:[],calls:[],interproceduralPaths:[],findings};}
}
class PowerShellSemanticAdapter{
  constructor({projectId,root,powerShellExecutable,helperPath=path.resolve(__dirname,'..','scripts','powershellSemanticAnalyzer.ps1')}){this.projectId=projectId;this.root=path.resolve(root);this.executable=path.resolve(powerShellExecutable);this.helperPath=path.resolve(helperPath);this.id='powershell-native-parser';this.worker=new SecureCompilerWorker({root:this.root,allowExecutables:[this.executable]});}
  async analyze({files}){for(const file of files)inside(this.root,file);const output=await this.worker.run(this.executable,['-NoLogo','-NoProfile','-NonInteractive','-File',this.helperPath,this.root,this.projectId,...files]);const parsed=JSON.parse(output.stdout);if(parsed.projectId!==this.projectId||parsed.adapter?.id!==this.id)throw new Error('PowerShell parser returned invalid project-bound output.');for(const finding of parsed.findings)normalizedFinding(finding);return{...parsed,custody:{stdoutSha256:output.stdoutSha256,stderrSha256:output.stderrSha256}};}
}
class ClangSemanticAdapter{
  constructor({projectId,root,clangExecutable=null}){this.projectId=projectId;this.root=path.resolve(root);this.executable=clangExecutable?path.resolve(clangExecutable):null;this.id='clang-json-ast';}
  health(){return{state:this.executable&&fs.existsSync(this.executable)?'healthy':'blocked',reason:this.executable?'clang-not-found':'clang-not-configured'};}
  async analyze({files,compileArgs=[]}){if(this.health().state!=='healthy')throw new Error('Clang is required for C/C++ semantic analysis.');const worker=new SecureCompilerWorker({root:this.root,allowExecutables:[this.executable]});const version=(await worker.run(this.executable,['--version'])).stdout.split(/\r?\n/)[0];const functions=new Map();const calls=[];const findings=[];const records=[];for(const file of files){const content=fs.readFileSync(inside(this.root,file),'utf8');records.push({file,sha256:sha(content)});const output=await worker.run(this.executable,[...compileArgs,'-Xclang','-ast-dump=json','-fsyntax-only',file]);const tree=JSON.parse(output.stdout);const stack=[];const visit=(node)=>{let entered=null;if(node.kind==='FunctionDecl'&&node.name){entered=`${file}#${node.name}`;functions.set(entered,{id:entered,file,start:node.range?.begin?.offset??0,end:(node.range?.end?.offset??0)+(node.range?.end?.tokLen??1),parameters:(node.inner||[]).filter((item)=>item.kind==='ParmVarDecl').map((item)=>item.name),sources:[],sinks:[]});stack.push(entered);}const current=stack.at(-1);if(current&&node.kind==='DeclRefExpr'&&SOURCE_NAMES.has(node.referencedDecl?.name))functions.get(current).sources.push({name:node.referencedDecl.name,start:node.range?.begin?.offset??0});if(node.kind==='CallExpr'){const refs=[];const collect=(item)=>{if(item.kind==='DeclRefExpr'&&item.referencedDecl?.name)refs.push(item.referencedDecl.name);for(const child of item.inner||[])collect(child);};collect(node);const name=refs[0]||'unresolved';const target=functions.has(`${file}#${name}`)?`${file}#${name}`:null;const start=node.range?.begin?.offset??0;const end=(node.range?.end?.offset??start)+(node.range?.end?.tokLen??1);calls.push({caller:current,calleeText:name,target,file,start,end});if(current&&SINK_NAMES.has(name)){functions.get(current).sinks.push({name,start});findings.push(normalizedFinding({projectId:this.projectId,language:/\.(?:cc|cpp|cxx|hpp)$/i.test(file)?'cpp':'c',kind:'semantic-security-sink',file,boundary:`${file}:${start}-${end}`,start,end,baseSha256:sha(content),toolId:this.id,toolVersion:version,callee:name}));}}for(const child of node.inner||[])visit(child);if(entered)stack.pop();};visit(tree);}
    const paths=[];for(const [start,entry] of functions)if(entry.sources.length){const queue=[[start]],seen=new Set([start]);while(queue.length){const chain=queue.shift(),last=chain.at(-1);if(functions.get(last)?.sinks.length){paths.push({functions:chain,source:entry.sources[0],sink:functions.get(last).sinks[0]});continue;}for(const call of calls.filter((item)=>item.caller===last&&item.target))if(!seen.has(call.target)){seen.add(call.target);queue.push([...chain,call.target]);}}}return{schemaVersion:1,projectId:this.projectId,adapter:{id:this.id,version},files:records,diagnostics:[],functions:[...functions.values()],calls,interproceduralPaths:paths,findings};}
}
class RoslynSemanticAdapter{
  constructor({projectId,root,dotnetExecutable,projectFile=path.resolve(__dirname,'..','tools','roslynSemanticAnalyzer','RoslynSemanticAnalyzer.csproj')}){this.projectId=projectId;this.root=path.resolve(root);this.executable=path.resolve(dotnetExecutable);this.projectFile=path.resolve(projectFile);this.id='roslyn';this.worker=new SecureCompilerWorker({root:this.root,allowExecutables:[this.executable],timeoutMs:60000});}
  async analyze({files}){for(const file of files)inside(this.root,file);const toolHome=fs.mkdtempSync(path.join(os.tmpdir(),'crucible-roslyn-home-'));try{const output=await this.worker.run(this.executable,['run','--project',this.projectFile,'--configuration','Release','--artifacts-path',path.join(toolHome,'artifacts'),'--',this.root,this.projectId,...files],{toolHome});const parsed=JSON.parse(output.stdout);if(parsed.projectId!==this.projectId||parsed.adapter?.id!==this.id)throw new Error('Roslyn returned invalid project-bound output.');for(const finding of parsed.findings)normalizedFinding(finding);return{...parsed,custody:{stdoutSha256:output.stdoutSha256,stderrSha256:output.stderrSha256}};}finally{fs.rmSync(toolHome,{recursive:true,force:true});}}
}
class JavaSemanticAdapter{
  constructor({projectId,root,javaExecutable,helperPath=path.resolve(__dirname,'..','scripts','JavaSemanticAnalyzer.java')}){this.projectId=projectId;this.root=path.resolve(root);this.executable=path.resolve(javaExecutable);this.helperPath=path.resolve(helperPath);this.id='jdk-compiler-tree';this.worker=new SecureCompilerWorker({root:this.root,allowExecutables:[this.executable],timeoutMs:60000});}
  async analyze({files}){for(const file of files)inside(this.root,file);const output=await this.worker.run(this.executable,[this.helperPath,this.root,this.projectId,...files]);const decode=(value)=>Buffer.from(value,'base64url').toString('utf8');const functions=[],calls=[],findings=[],records=[];let version='unknown';for(const line of output.stdout.trim().split(/\r?\n/)){const parts=line.split('|');if(parts[0]==='META'){if(decode(parts[1])!==this.projectId)throw new Error('Java analyzer project binding failed.');version=decode(parts[2]);}if(parts[0]==='FILE')records.push({file:decode(parts[1]),sha256:parts[2]});if(parts[0]==='FUNCTION')functions.push({file:decode(parts[1]),id:decode(parts[2]),start:Number(parts[3]),end:Number(parts[4]),parameters:decode(parts[5]).split(',').filter(Boolean),sources:[],sinks:[]});if(parts[0]==='CALL')calls.push({file:decode(parts[1]),caller:decode(parts[2])||null,calleeText:decode(parts[3]),target:decode(parts[4])||null,start:Number(parts[5]),end:Number(parts[6])});if(parts[0]==='FINDING'){const file=decode(parts[1]),callee=decode(parts[2]),start=Number(parts[3]),end=Number(parts[4]);findings.push(normalizedFinding({projectId:this.projectId,language:'java',kind:'semantic-security-sink',file,boundary:`${file}:${start}-${end}`,start,end,baseSha256:parts[5],toolId:this.id,toolVersion:version,callee}));}}return{schemaVersion:1,projectId:this.projectId,adapter:{id:this.id,version},files:records,diagnostics:[],functions,calls,interproceduralPaths:[],findings,custody:{stdoutSha256:output.stdoutSha256,stderrSha256:output.stderrSha256}};}
}
function composeSemanticGraph({projectId,reports,bindings=[]}){if(!Array.isArray(reports)||reports.some((item)=>item.projectId!==projectId))throw new Error('Semantic graph requires project-bound reports.');const nodes=new Map(),edges=[];for(const report of reports){for(const fn of report.functions||[])nodes.set(fn.id,{id:fn.id,language:report.findings?.[0]?.language||report.adapter.id,file:fn.file,sources:fn.sources||[],sinks:fn.sinks||[]});for(const call of report.calls||[])if(call.caller&&call.target)edges.push({from:call.caller,to:call.target,kind:'native-call',proofStageSatisfied:false});}for(const binding of bindings){if(!nodes.has(binding.from)||!nodes.has(binding.to)||typeof binding.kind!=='string'||!binding.kind)throw new Error('Cross-language bindings must reference exact known symbols.');edges.push({from:binding.from,to:binding.to,kind:binding.kind,proofStageSatisfied:false});}const paths=[];for(const node of nodes.values())if(node.sources.length){const queue=[[node.id]],seen=new Set([node.id]);while(queue.length){const chain=queue.shift(),last=chain.at(-1),target=nodes.get(last);if(target?.sinks.length){paths.push({functions:chain,source:node.sources[0],sink:target.sinks[0],proofStageSatisfied:false});continue;}for(const edge of edges.filter((item)=>item.from===last))if(!seen.has(edge.to)){seen.add(edge.to);queue.push([...chain,edge.to]);}}}return{schemaVersion:1,projectId,nodes:[...nodes.values()],edges,paths,proofStageSatisfied:false,promotionAuthorized:false};}
class SemanticAnalysisCoordinator{constructor({projectId,adapters={}}){this.projectId=projectId;this.adapters=adapters;}health(){const organs={};for(const [language,adapter] of Object.entries(this.adapters))organs[language]=adapter?'healthy':'blocked';const blocked=Object.values(organs).filter((state)=>state==='blocked').length;return{projectId:this.projectId,state:blocked===0?'healthy':blocked===Object.keys(organs).length?'inhibited':'degraded',organs};}analyze(language,input){const adapter=this.adapters[language];if(!adapter)throw new Error(`Semantic adapter unavailable for ${language}.`);return adapter.analyze(input);}}
module.exports={normalizedFinding,SecureCompilerWorker,TypeScriptSemanticAdapter,PythonSemanticAdapter,WebStandardsSemanticAdapter,ShellSemanticAdapter,PowerShellSemanticAdapter,ClangSemanticAdapter,RoslynSemanticAdapter,JavaSemanticAdapter,composeSemanticGraph,SemanticAnalysisCoordinator};
